export const BRAND = {
  name: "Physique 57 India",
  product: "IRIS Command",
  tagline: "Member care, choreographed.",
};

export const STUDIOS = [
  {
    id: "kwality",
    name: "Kwality House, Kemps Corner",
    city: "Mumbai",
    region: "Mumbai",
    studioIds: [1],
    address: "Kwality House, Kemps Corner, Mumbai",
  },
  {
    id: "supreme",
    name: "Supreme HQ, Bandra",
    city: "Mumbai",
    region: "Bandra",
    studioIds: [2],
    address: "Supreme HQ, Bandra, Mumbai",
  },
  {
    id: "kenkere",
    name: "Kenkere House, Bengaluru",
    city: "Bengaluru",
    region: "Bengaluru",
    studioIds: [3],
    address: "Kenkere House, Bengaluru",
  },
  {
    id: "courtside",
    name: "Courtside, Mumbai",
    city: "Mumbai",
    region: "Mumbai",
    studioIds: [1],
    address: "Courtside, Mumbai",
  },
  {
    id: "copper",
    name: "the Studio by Copper & Cloves, Bengaluru",
    city: "Bengaluru",
    region: "Bengaluru",
    studioIds: [3],
    address: "the Studio by Copper & Cloves, Bengaluru",
  },
] as const;

export const CLASS_FORMATS = [
  "Studio Hosted Class",
  "Studio FIT",
  "Studio Back Body Blaze",
  "Studio Barre 57",
  "Studio Mat 57",
  "Studio Trainer's Choice",
  "Studio Cardio Barre Express",
  "Studio Amped Up!",
  "Studio HIIT",
  "Studio Foundations",
  "Studio SWEAT In 30",
  "Studio Cardio Barre Plus",
  "Studio Barre 57 Express",
  "Studio Cardio Barre",
  "Studio Back Body Blaze Express",
  "Studio Recovery",
  "Studio Pre/Post Natal",
  "Studio Mat 57 Express",
  "Studio PowerCycle",
  "Studio PowerCycle Express",
  "Studio Strength Lab (Full Body)",
  "Studio Strength Lab (Pull)",
  "Studio Strength Lab (Push)",
  "Studio Strength Lab",
] as const;

export const STUDIO_AREAS = [
  "Main studio floor",
  "Reception / lobby",
  "Locker room",
  "Showers / washroom",
  "Member lounge",
  "Boutique",
  "Parking / valet",
  "Back office",
  "Staircase / corridor",
  "Cycle studio",
  "Strength Lab floor",
] as const;

export const SYSTEMS = [
  "Momence",
  "POS / card machine",
  "Wi-Fi / router",
  "Front desk iPad",
  "Website / mobile app",
  "Payment gateway (Stripe / Razorpay)",
  "Audio / mic system",
  "CCTV / surveillance",
  "Access control / door lock",
  "Cash counting machine",
  "Yellow Messenger",
  "Other system",
] as const;

export const OCCURRED_OPTIONS = [
  "Just now",
  "Earlier today",
  "Yesterday",
  "Earlier this week",
  "Last week",
  "Ongoing / recurring",
] as const;

export const REPORTED_BY_OPTIONS = [
  "I noticed this myself",
  "A member told me about it",
  "A colleague flagged it to me",
  "Raised during a walkthrough / audit",
] as const;

export const TRAINERS = [
  "Anisha Shah",
  "Anmol Sharma",
  "Atulan Purohit",
  "Bret Saldanha",
  "Cauveri Vikrant",
  "Chaitanya Nahar",
  "Kajol Kanchan",
  "Karan Bhatia",
  "Karanvir Bhatia",
  "Mrigakshi Jaiswal",
  "Pranjali Jain",
  "Pushyank Nahar",
  "Raunak Khemuka",
  "Reshma Sharma",
  "Richard D'Costa",
  "Rohan Dahima",
  "Shruti Kulkarni",
  "Siddhartha Kusuma",
  "Simonelle De Vitre",
  "Vivaran Dhasmana",
] as const;

export const MEMBERSHIPS = [
  "Barre 1 month Unlimited",
  "Barre 2 week Unlimited",
  "Barre 3 months Unlimited",
  "Barre 6 month Unlimited",
  "Barre Annual Membership",
  "Newcomers 2 For 1",
  "Owner's Special - 2 for 1",
  "powerCycle 1 month Unlimited",
  "powerCycle 2 week Unlimited",
  "powerCycle 3 months Unlimited",
  "powerCycle 6 months Unlimited",
  "powerCycle Annual Membership",
  "Strength Lab 1 month Unlimited",
  "Strength Lab 2 week Unlimited",
  "Strength Lab 3 months Unlimited",
  "Strength Lab 6 months Unlimited",
  "Strength Lab Annual Membership",
  "Studio 1 Month Unlimited Membership",
  "Studio 10 Single Class Pack",
  "Studio 12 Class Package",
  "Studio 2 Week Unlimited Membership",
  "Studio 20 Single Class Pack",
  "Studio 3 Month U/L Monthly Installment",
  "Studio 3 Month Unlimited Membership",
  "Studio 30 Single Class Pack",
  "Studio 4 Class Package",
  "Studio 6 Month Unlimited Membership",
  "Studio 8 Class Package",
  "Studio Annual Membership - Monthly Intsallment",
  "Studio Annual Unlimited Membership",
  "Studio Extended 10 Single Class Pack",
  "Studio Happy Hour Private",
  "Studio Newcomers 2 Week Unlimited Membership",
  "Studio Private - Anisha (Single Class)",
  "Studio Private Class",
  "Studio Private Class X 10",
  "Studio Privates - Anisha x 10",
  "Studio Single Class",
  "Summer Bootcamp - Studio 6 Week Unlimited",
  "Virtual Private - Anisha",
  "Virtual Private Class",
  "Virtual Private Class X 10",
  "Virtual Privates - Anisha x 10",
] as const;

export const CATEGORY_MAP: Record<string, string[]> = {
  Scheduling: [
    "Time Change",
    "Level Change",
    "Additional Classes",
    "Trainer Preferences",
    "Class Capacity Issues",
    "Waitlist Concerns",
    "Studio Timings",
    "Session Length",
    "Cancellation Policy",
    "Booking Restrictions",
    "Class Substitutions",
    "Trainer Substitutions",
    "Last-minute Cancellations",
    "Late Arrival Policy",
    "Special Request Accommodations",
    "Early Morning/Late Night Class Availability",
    "Weekend vs. Weekday Class Balance",
    "Rescheduling Flexibility",
    "Booking Confirmation Issues",
    "Holiday and Festival Class Planning",
  ],
  "Class Experience": [
    "Bad Odour",
    "Audio Issues",
    "Studio Temperature Too Hot/Cold",
    "Overcrowding in Class",
    "Class Flow and Pacing",
    "Modifications in Routine",
    "Engagement with Clients",
    "Hands-on Adjustments",
    "Demonstration and Visual Cues",
    "Knowledge and Competence",
    "Brand Language Usage",
    "Grooming and Appearance",
    "Attendance for Workshops",
    "Attendance for Meetings",
    "Class Format Satisfaction",
    "Class Duration Suitability",
    "Instructor Energy and Motivation",
    "Class Variety and Themes",
    "Adjustments for Different Fitness Levels",
    "Challenges in Following Instructor",
  ],
  "Trainer Feedback": [
    "Trainer Forgot Names",
    "Class Intensity Too High/Low",
    "Trainer Hygiene",
    "Trainer Punctuality Issues",
    "Trainer Behaviour",
    "Modifications in Routine",
    "Engagement with Clients",
    "Hands-on Adjustments",
    "Demonstration and Visual Cues",
    "Knowledge and Competence",
    "Brand Language Usage",
    "Pre and Post-Class Outreach",
    "Trainer Availability",
    "Feedback Handling",
    "Emergency Preparedness",
    "Trainer Focus on Individual Needs",
    "Class Ending on Time",
    "Trainer Encouragement",
    "Injury Prevention and Safety",
    "Too Many Corrections vs. Too Few",
  ],
  "Repair and Maintenance": [
    "AC and HVAC Issues",
    "TFA Malfunction",
    "Lighting Issues",
    "Studio System Malfunction",
    "Pest Control Needed",
    "Staff Uniforms Not Clean",
    "Toiletries and Supplies Low",
    "Towel Availability Issues",
    "Plumbing Leaks",
    "General Maintenance Delays",
    "Uncomfortable Lounge Seating",
    "Air Fresheners Too Strong",
    "Music System Too Loud/Low",
    "Vending Machine Out of Stock",
    "Additional Waiting Area Seating",
    "Door Lock Issues",
    "Fire Safety Compliance",
    "Water Dispenser Issues",
    "Dust and Mold in Corners",
    "Broken Equipment Not Repaired",
  ],
  "Studio Amenities and Facilities": [
    "Studio Odour and Aroma",
    "Cleanliness and Hygiene",
    "Ventilation Poor",
    "Air Quality Poor",
    "Valet Issues",
    "Locker Availability",
    "Shower Water Pressure",
    "Steam Room Not Working",
    "Boutique Availability Issues",
    "Wi-Fi Slow",
    "Integration Issues",
    "Lost and Found Disorganization",
    "Availability of Gym Accessories",
    "Fitness Challenges and Rewards",
    "Additional Membership Perks",
    "Smoothie Bar and Refreshments",
    "Member Lounge Cleanliness",
    "Community Events and Social Engagement",
    "Holiday-Themed Classes",
    "Sustainable and Eco-Friendly Practices",
  ],
  "Operating Systems": [
    "Moments Notice",
    "Stripe and Razorpay",
    "Yellow Messenger",
    "Website Glitches",
    "Router Connectivity",
    "iPad Functionality",
    "Cash Counting Machine Issues",
    "POS System Malfunctions",
    "CRM System Errors",
    "Data Security Issues",
    "Technical Assistance",
    "Difficulty Tracking Sessions",
    "System Delays",
    "Software Bugs",
    "Mobile App UI/UX Issues",
    "Attendance Record Discrepancies",
    "Missed Sessions Not Recorded",
    "Mobile App Freezing",
    "Delayed Notifications",
    "Error in Class Listings",
  ],
  "Tech Issues": [
    "Laptops Not Functioning",
    "Speakers Static Noise",
    "Mic Not Working",
    "Phones Not Working",
    "App Performance Bugs",
    "Booking System Errors",
    "Password and Login Issues",
    "Payment Processing Delays",
    "Online Class Streaming Buffering",
    "Notifications Not Received",
    "Auto-Debit Incorrect Charges",
    "Social Media Glitches",
    "Wrong Class Bookings",
    "Incorrect Charges on Account",
    "Studio Music Preferences",
    "Camera Surveillance Issues",
    "Digital Receipts and Invoices",
    "Website Navigation Difficulties",
    "Virtual Class Video Quality",
    "Studio Wi-Fi Not Working",
  ],
  "Pricing and Memberships": [
    "Price Transparency",
    "Membership Flexibility",
    "Discounts and Offers Confusion",
    "Refund and Cancellation Policy Issue",
    "Auto-Renewal Concerns",
    "Transparency in TandC/",
    "Add-on Services Pricing Clarity",
    "Class Pack Expiry Confusion",
    "Private Session Pricing",
    "Membership Upgrade/Downgrade",
    "Lack of Payment Plan Options",
    "Referral Discount Issues",
    "Holiday and Special Pricing Clarity",
    "Corporate Wellness Program Pricing",
    "Pricing for International Clients",
    "Membership Pause and Freeze Policy",
    "Special Group Discounts",
    "Loyalty Program Issues",
  ],
  "Customer Service and Communication": [
    "Delay in Response",
    "Unresolved Complaints",
    "Front Desk Attitude",
    "Miscommunication on Offers",
    "Response Time to Queries",
    "Follow-up Post Inquiry",
    "Friendliness and Approachability",
    "Call Handling Etiquette",
    "Clarity in Policies",
    "Late Response to Complaints",
    "Handling of Complaints",
    "Feedback Follow-up Process",
    "Compensation for Service Issues",
    "Customer Retention Strategies",
    "Over-promising and Under-delivery",
    "Response to Negative Reviews",
    "Training of Customer Service Team",
    "Training of Sales Team",
    "Knowledge of Membership Policies",
    "Proactive Client Engagement",
  ],
  "Brand Feedback": [
    "Brand Positioning",
    "Brand Identity Consistency",
    "Marketing Message Accuracy",
    "Brand Tone Consistency",
    "Social Media Engagement",
    "Advertising Consistency",
    "Collaborations and Partnerships",
    "Merchandise Quality",
    "Member Recognition Efforts",
    "Influencer Engagement",
    "Staff Wearing Incorrect Branding",
    "Merchandise Display Issues",
    "Branded Content Guidelines",
    "Member Recognition Events",
    "Newsletter Effectiveness",
    "Brand Perception in Market",
    "Perception of Pricing Value",
    "Client Testimonials Management",
    "Client Loyalty Recognition",
    "Brand Event Participation",
  ],
  "Safety and Security": [
    "Emergency Exits Blocked",
    "Panic Button Malfunction",
    "Unlocked Doors",
    "CCTV Malfunction",
    "Security Guard Issues",
    "Client Harassment Reports",
    "Fire Drills Not Conducted",
    "Suspicious Individuals Inside Studio",
    "Front Desk Not Checking IDs",
    "Unregistered Walk-ins",
    "Trespassing Concerns",
    "Personal Safety Concerns",
    "Harassment Reports",
    "Data Breach Concerns",
    "Employee Security Training",
    "Reporting Suspicious Activity",
    "Staff Security Concerns",
    "Handling of Medical Emergencies",
    "First Aid Kit Availability",
    "Unauthorized Use of Equipment",
  ],
  "Theft and Lost Items": [
    "Locker Theft",
    "Stolen Personal Items",
    "Misplaced Valuables",
    "Items Taken from Boutique",
    "Items Left Behind by Clients",
    "Studio Lost and Found Management",
    "Staff Theft",
    "Reporting Stolen Items",
    "Theft Prevention Measures",
    "Theft Investigation Process",
    "Personal Items Taken from Trainer Area",
    "Issues with Valet Theft",
    "Theft by Other Members",
    "Lost Shoes/Workout Gear",
    "Safe Storage for Client Bags",
    "Clients Forgetting Items in Studio",
    "Missing Towels",
    "Theft During Busy Hours",
    "Members Taking Extra Equipment",
    "Coffee and Refreshments Options",
  ],
  Miscellaneous: [
    "Music Volume Issues",
    "Studio Decor and Ambience",
    "Mobile Charging Stations",
    "Late-Night Class Safety",
    "Noise Complaints from Neighbors",
    "Misplaced Equipment",
    "Temperature Control Inconsistency",
    "Scent Sensitivities",
    "Lighting Preferences",
    "Cold Air Drafts",
    "Overcrowding in Lobby",
    "Construction Noise Nearby",
    "Child-Friendly Facilities",
    "Outdoor Signage Visibility",
    "Feedback Fatigue",
    "Personal Storage Lockers Needed",
    "Background Music Selection",
    "Social Media Response Time",
    "Customer Flow Management",
  ],
};

export const CATEGORIES = Object.keys(CATEGORY_MAP);

export const DEPARTMENT_RECORDS = [
  { id: "accounts", name: "Accounts", description: "Accounts routing queue", active: true },
  {
    id: "customer-service",
    name: "Customer Service",
    description: "Customer Service routing queue",
    active: true,
  },
  { id: "management", name: "Management", description: "Management routing queue", active: true },
  { id: "marketing", name: "Marketing", description: "Marketing routing queue", active: true },
  { id: "operations", name: "Operations", description: "Operations routing queue", active: true },
  {
    id: "sales-client-servicing",
    name: "Sales & Client Servicing",
    description: "Sales & Client Servicing routing queue",
    active: true,
  },
  { id: "training", name: "Training", description: "Training routing queue", active: true },
] as const;

export const CATEGORY_DEPARTMENT: Record<string, string> = {
  Scheduling: "operations",
  "Class Experience": "training",
  "Trainer Feedback": "training",
  "Repair and Maintenance": "operations",
  "Studio Amenities and Facilities": "operations",
  "Operating Systems": "operations",
  "Tech Issues": "operations",
  "Pricing and Memberships": "accounts",
  "Customer Service and Communication": "sales-client-servicing",
  "Brand Feedback": "marketing",
  "Safety and Security": "management",
  "Theft and Lost Items": "operations",
  Miscellaneous: "operations",
};

export type StaffRecord = {
  id: number;
  externalId: string;
  name: string;
  email: string;
  role: string;
  department: string;
  location: string;
  manager: string | null;
  studioId: number | null;
  categories: string[];
  avatarColor: string;
  isActive: boolean;
};

export const STAFF: StaffRecord[] = [
  {
    id: 1,
    externalId: "accounts-physique57mumbai-com",
    name: "Sagar Ingole",
    email: "accounts@physique57mumbai.com",
    role: "Associate",
    department: "Operations",
    location: "Physique 57, Mumbai",
    manager: "Zahur Shaikh",
    studioId: 1,
    categories: [
      "Scheduling",
      "Repair and Maintenance",
      "Studio Amenities and Facilities",
      "Operating Systems",
      "Tech Issues",
      "Theft and Lost Items",
      "Miscellaneous",
    ],
    avatarColor: "#ec4899",
    isActive: true,
  },
  {
    id: 2,
    externalId: "akshay-physique57mumbai-com",
    name: "Akshay Rane",
    email: "akshay@physique57mumbai.com",
    role: "Sr. Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#0ea5e9",
    isActive: true,
  },
  {
    id: 3,
    externalId: "anisha-physique57india-com",
    name: "Anisha Shah",
    email: "anisha@physique57india.com",
    role: "Master Trainer",
    department: "Training",
    location: "India",
    manager: "Mallika Parekh",
    studioId: null,
    categories: ["Class Experience", "Trainer Feedback"],
    avatarColor: "#14b8a6",
    isActive: true,
  },
  {
    id: 4,
    externalId: "api-physique57bengaluru-com",
    name: "Api Serou",
    email: "api@physique57bengaluru.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bengaluru",
    manager: "Shifa Ali",
    studioId: 3,
    categories: ["Customer Service and Communication"],
    avatarColor: "#ec4899",
    isActive: true,
  },
  {
    id: 5,
    externalId: "deesha-physique57mumbai-com",
    name: "Deesha Changwani",
    email: "deesha@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bandra",
    manager: "Jimmeey Gondaa",
    studioId: 2,
    categories: ["Customer Service and Communication"],
    avatarColor: "#14b8a6",
    isActive: true,
  },
  {
    id: 6,
    externalId: "gaurav-physique57mumbai-com",
    name: "Gaurav Sogam",
    email: "gaurav@physique57mumbai.com",
    role: "Accounts Assistant",
    department: "Accounts",
    location: "Physique 57, Mumbai",
    manager: "Sachin Nalawade",
    studioId: 1,
    categories: ["Pricing and Memberships"],
    avatarColor: "#3b82f6",
    isActive: true,
  },
  {
    id: 7,
    externalId: "imran-physique57mumbai-com",
    name: "Imran Shaikh",
    email: "imran@physique57mumbai.com",
    role: "Sr. Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bandra",
    manager: "Jimmeey Gondaa",
    studioId: 2,
    categories: ["Customer Service and Communication"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 8,
    externalId: "jhanavi-physique57india-com",
    name: "Jhanvi Chhaya",
    email: "Jhanavichhaya11@gmail.com",
    role: "Social Media",
    department: "Marketing",
    location: "Physique 57, India",
    manager: "Reyna",
    studioId: null,
    categories: ["Brand Feedback"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 9,
    externalId: "jimmeey-physique57india-com",
    name: "Jimmeey Gondaa",
    email: "jimmeey@physique57india.com",
    role: "Head of Sales & Client Servicing",
    department: "Sales & Client Servicing",
    location: "India",
    manager: "Mitali Kumar",
    studioId: null,
    categories: ["Customer Service and Communication"],
    avatarColor: "#3b82f6",
    isActive: true,
  },
  {
    id: 10,
    externalId: "mallika-physique57india-com",
    name: "Mallika Parekh",
    email: "mallika@physique57india.com",
    role: "Owner",
    department: "Management",
    location: "India",
    manager: "Board",
    studioId: null,
    categories: ["Safety and Security"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 11,
    externalId: "mitali-physique57india-com",
    name: "Mitali Kumar",
    email: "mitali@physique57india.com",
    role: "Chief Operations Officer",
    department: "Management",
    location: "India",
    manager: "Mallika Parekh",
    studioId: null,
    categories: ["Safety and Security"],
    avatarColor: "#3b82f6",
    isActive: true,
  },
  {
    id: 12,
    externalId: "mrigakshi-physique57mumbai-com",
    name: "Mrigakshi Jaiswal",
    email: "mrigakshi@physique57mumbai.com",
    role: "Head Trainer",
    department: "Training",
    location: "Mumbai",
    manager: "Anisha Shah",
    studioId: 1,
    categories: ["Class Experience", "Trainer Feedback"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 13,
    externalId: "nadiya-physique57mumbai-com",
    name: "Nadiya Shaikh",
    email: "nadiya@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#10b981",
    isActive: true,
  },
  {
    id: 14,
    externalId: "prathap-physique57bengaluru-com",
    name: "Prathap K P",
    email: "prathap@physique57bengaluru.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bengaluru",
    manager: "Shifa Ali",
    studioId: 3,
    categories: ["Customer Service and Communication"],
    avatarColor: "#10b981",
    isActive: true,
  },
  {
    id: 15,
    externalId: "pujal-physique57mumbai-com",
    name: "Pujal Jathar",
    email: "pujal@physique57mumbai.com",
    role: "Sr. Finance & Accounts Executive",
    department: "Accounts",
    location: "Physique 57, Bengaluru",
    manager: "Sachin Nalawade",
    studioId: 3,
    categories: ["Pricing and Memberships"],
    avatarColor: "#ec4899",
    isActive: true,
  },
  {
    id: 16,
    externalId: "pushyank-physique57bengaluru-com",
    name: "Pushyank Nahar",
    email: "pushyank@physique57bengaluru.com",
    role: "Head Trainer",
    department: "Training",
    location: "Bengaluru",
    manager: "Anisha Shah",
    studioId: 3,
    categories: ["Class Experience", "Trainer Feedback"],
    avatarColor: "#f59e0b",
    isActive: true,
  },
  {
    id: 17,
    externalId: "rasika-physique57mumbai-com",
    name: "Rasika Kalambe",
    email: "rasika@physique57mumbai.com",
    role: "Accounts Executive",
    department: "Accounts",
    location: "Physique 57, Bengaluru",
    manager: "Sachin Nalawade",
    studioId: 3,
    categories: ["Pricing and Memberships"],
    avatarColor: "#8b5cf6",
    isActive: true,
  },
  {
    id: 18,
    externalId: "reyna-physique57india-com",
    name: "Reyna Jagtiani",
    email: "jagtianireyna@gmail.com",
    role: "Marketing Lead",
    department: "Marketing",
    location: "Physique 57, India",
    manager: "Mitali Kumar",
    studioId: null,
    categories: ["Brand Feedback"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 19,
    externalId: "saachi-physique57india-com",
    name: "Saachi Shetty",
    email: "saachi@physique57india.com",
    role: "Ops Manager",
    department: "Operations",
    location: "India",
    manager: "Mitali Kumar",
    studioId: null,
    categories: [
      "Scheduling",
      "Repair and Maintenance",
      "Studio Amenities and Facilities",
      "Operating Systems",
      "Tech Issues",
      "Theft and Lost Items",
      "Miscellaneous",
    ],
    avatarColor: "#ef4444",
    isActive: true,
  },
  {
    id: 20,
    externalId: "saachi-s-physique57bengaluru-com",
    name: "Saachi Shetty Jr",
    email: "saachi.s@physique57bengaluru.com",
    role: "Marketing Lead",
    department: "Marketing",
    location: "Bengaluru",
    manager: "Shifa Ali",
    studioId: 3,
    categories: ["Brand Feedback"],
    avatarColor: "#0ea5e9",
    isActive: true,
  },
  {
    id: 21,
    externalId: "sachin-physique57mumbai-com",
    name: "Sachin Nalawade",
    email: "sachin@physique57mumbai.com",
    role: "Accounts Head",
    department: "Accounts",
    location: "Physique 57, India",
    manager: "Mitali Kumar",
    studioId: null,
    categories: ["Pricing and Memberships"],
    avatarColor: "#3b82f6",
    isActive: true,
  },
  {
    id: 22,
    externalId: "sashi-physique57bengaluru-com",
    name: "Sashi Singh",
    email: "sashi@physique57bengaluru.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bengaluru",
    manager: "Shifa Ali",
    studioId: 3,
    categories: ["Customer Service and Communication"],
    avatarColor: "#14b8a6",
    isActive: true,
  },
  {
    id: 23,
    externalId: "sheetal-physique57mumbai-com",
    name: "Sheetal Kataria",
    email: "sheetal@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#ec4899",
    isActive: true,
  },
  {
    id: 24,
    externalId: "shifa-physique57bengaluru-com",
    name: "Shifa Ali",
    email: "shifa@physique57bengaluru.com",
    role: "Regional Head of Ops - South",
    department: "Operations",
    location: "Bengaluru",
    manager: "Mitali Kumar",
    studioId: 3,
    categories: [
      "Scheduling",
      "Repair and Maintenance",
      "Studio Amenities and Facilities",
      "Operating Systems",
      "Tech Issues",
      "Theft and Lost Items",
      "Miscellaneous",
    ],
    avatarColor: "#0ea5e9",
    isActive: true,
  },
  {
    id: 25,
    externalId: "shipra-physique57mumbai-com",
    name: "Shipra Pinge",
    email: "shipra@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bandra",
    manager: "Jimmeey Gondaa",
    studioId: 2,
    categories: ["Customer Service and Communication"],
    avatarColor: "#8b5cf6",
    isActive: true,
  },
  {
    id: 26,
    externalId: "tahira-physique57mumbai-com",
    name: "Taahira Sayyed",
    email: "tahira@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#0ea5e9",
    isActive: true,
  },
  {
    id: 27,
    externalId: "vahishta-physique57mumbai-com",
    name: "Vahishta Fitter",
    email: "vahishta@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#10b981",
    isActive: true,
  },
  {
    id: 28,
    externalId: "vivaran-physique57mumbai-com",
    name: "Vivaran Dhasmana",
    email: "vivaran@physique57mumbai.com",
    role: "Head Trainer",
    department: "Training",
    location: "Mumbai",
    manager: "Anisha Shah",
    studioId: 1,
    categories: ["Class Experience", "Trainer Feedback"],
    avatarColor: "#a855f7",
    isActive: true,
  },
  {
    id: 29,
    externalId: "yashas-physique57bengaluru-com",
    name: "Yashas K",
    email: "yashas@physique57bengaluru.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Bengaluru",
    manager: "Shifa Ali",
    studioId: 3,
    categories: ["Customer Service and Communication"],
    avatarColor: "#f59e0b",
    isActive: true,
  },
  {
    id: 30,
    externalId: "zaheer-physique57mumbai-com",
    name: "Zaheer Agarbattiwala",
    email: "zaheer@physique57mumbai.com",
    role: "Sales & Client Servicing Associate",
    department: "Sales & Client Servicing",
    location: "Physique 57, Mumbai",
    manager: "Jimmeey Gondaa",
    studioId: 1,
    categories: ["Customer Service and Communication"],
    avatarColor: "#8b5cf6",
    isActive: true,
  },
  {
    id: 31,
    externalId: "zahur-physique57mumbai-com",
    name: "Zahur Shaikh",
    email: "zahur@physique57mumbai.com",
    role: "Studio Coordinator",
    department: "Operations",
    location: "Physique 57, Mumbai",
    manager: "Saachi Shetty",
    studioId: 1,
    categories: [
      "Scheduling",
      "Repair and Maintenance",
      "Studio Amenities and Facilities",
      "Operating Systems",
      "Tech Issues",
      "Theft and Lost Items",
      "Miscellaneous",
    ],
    avatarColor: "#3b82f6",
    isActive: true,
  },
];

export const STATUS_LABELS: Record<string, string> = {
  recorded: "Recorded",
  new: "New",
  triaged: "Triaged",
  assigned: "Assigned",
  in_progress: "In progress",
  waiting_on_member: "Waiting on member",
  waiting_on_vendor: "Waiting on vendor",
  resolved: "Resolved",
  closed: "Closed",
};

export const PRIORITY_SLA_HOURS: Record<string, number> = {
  critical: 1,
  high: 4,
  medium: 24,
  low: 72,
};

export const CATEGORY_ICONS: Record<string, string> = {
  Scheduling: "CalendarClock",
  "Class Experience": "Sparkles",
  "Trainer Feedback": "UserRound",
  "Repair and Maintenance": "Wrench",
  "Studio Amenities and Facilities": "Building2",
  "Operating Systems": "MonitorCog",
  "Tech Issues": "Cpu",
  "Pricing and Memberships": "CreditCard",
  "Customer Service and Communication": "MessageCircleHeart",
  "Brand Feedback": "BadgeCheck",
  "Safety and Security": "ShieldAlert",
  "Theft and Lost Items": "PackageSearch",
  Miscellaneous: "Layers",
};
