import {CATEGORY_MAP,CLASS_FORMATS,STUDIO_AREAS,SYSTEMS,OCCURRED_OPTIONS,MEMBERSHIPS} from './constants';
import type {GuidedTemplate,StructuredField} from './ticket-contract';
import {slugify} from './utils';
const select=(id:string,label:string,options:readonly string[],required=true,helper?:string):StructuredField=>({id,label,type:'select',options:[...options],required,helper});
const text=(id:string,label:string,required=true,helper?:string):StructuredField=>({id,label,type:'textarea',required,helper});
const num=(id:string,label:string,required=false,helper?:string):StructuredField=>({id,label,type:'number',required,helper});
const attribution='Adapted from Iris Ai intake workflows and Fillout trainer evaluations';
const baseFields:StructuredField[]=[select('impact','How much did this affect the member or the floor?',['Minor inconvenience','Noticeably affected the experience','Member or class could not proceed as normal','Safety concern']),text('requestedResolution','What needs to happen next?',false,'What would a good outcome look like — a fix, a follow-up, a policy check?')];
const rubric=(prefix:string,items:[string,number][]):StructuredField[]=>items.map(([label,weight],i)=>({id:prefix+i,label,type:'rating',required:true,weight,section:'Assessment scorecard'}));
const powerCycle: [string,number][]=[['Attendance & bike fill rate',12.5],['Retention & repeat riders',12.5],['Member connection',12.5],['Member feedback',12.5],['Motivation & USP',8],['Musicality & beat matching',10],['Energy, vocals & command',10],['Programming & sequencing',8],['Safety, setup & form',8],['Work ethics & core values',6]];
const barre: [string,number][]=[['Client attendance',12.5],['Client retention',12.5],['Client outreach, communication and connection',12.5],['Client feedback',12.5],['Mindful moment / USP integration / Motivation',8],['Musicality',8],['Energy and vocals',8],['Choreography and sequencing',8],['Learning styles and use of names',8],['Classes, workshops, meetings and core values',10]];
const strength: [string,number][]=[['Pre-class setup',8],['Verbal cues',8],['Visual demonstrations',8],['Injury modifications',8],['Level-appropriate modifications',8],['Motivation & connection',8],['Music choices',7],['Space & equipment',7],['Time management & flow',7],['Use of member names',7],['Overall energy',8],['Mindful moment',8],['Post-class spiel',8]];

/** Category-aware default field set — every subcategory across the taxonomy gets
 *  tailored, relevant guided fields instead of one generic fallback. This is what
 *  gives the library real depth beyond the handful of hand-curated flagship templates. */
function defaultFieldsForCategory(category:string):StructuredField[]{
  const withBase=(...fields:StructuredField[])=>[...fields,...baseFields];
  if(['Scheduling','Class Experience','Trainer Feedback'].includes(category))
    return withBase(select('occurredWhen','When did this happen?',OCCURRED_OPTIONS),text('narrative','Exactly what happened',true,'Include the class time, what was said or done, and who was involved.'));
  if(['Repair and Maintenance','Studio Amenities and Facilities'].includes(category))
    return withBase(select('area','Where in the studio',STUDIO_AREAS),select('occurredWhen','When did this happen?',OCCURRED_OPTIONS),select('classImpact','Is it blocking a class right now?',['Yes, blocking now','Not yet, but it will be','No, comfort / back-office only']),text('immediateAction','Immediate action already taken',false));
  if(['Operating Systems','Tech Issues'].includes(category))
    return withBase(select('systemName','Which system or equipment',SYSTEMS),select('occurredWhen','When did this happen?',OCCURRED_OPTIONS),text('errorDetail','What exactly happened',true,'Error message, screen it froze on, what you tried already.'));
  if(category==='Pricing and Memberships')
    return withBase(select('membershipRef','Membership / package',MEMBERSHIPS,false),num('amount','Amount involved (₹)',false),text('transactionRef','Transaction / invoice reference',false));
  if(['Customer Service and Communication','Brand Feedback'].includes(category))
    return withBase(select('channelOfIssue','Where did this happen?',['Front desk','Phone','WhatsApp','Email','Instagram / social','Website','In studio']));
  if(category==='Safety and Security')
    return[select('isImmediateDanger','Is anyone in immediate danger right now?',['Yes — happening now','No, but it needs urgent attention'],true),select('alreadyReported','Has this already been flagged to a manager or security?',['Yes','Not yet']),text('narrative','Exactly what happened',true),text('requestedResolution','What needs to happen next?',false)];
  if(category==='Theft and Lost Items')
    return[text('itemDescription','What item is missing / found?',true,'Brand, colour, distinguishing marks.'),select('lastSeen','Where was it last seen?',['Locker','Studio floor','Lounge','Valet','Boutique','Changing room']),select('occurredWhen','When did this happen?',OCCURRED_OPTIONS),text('requestedResolution','What needs to happen next?',false)];
  return withBase(select('occurredWhen','When did this happen?',OCCURRED_OPTIONS));
}

export const SPECIAL_TEMPLATES:GuidedTemplate[]=[
{id:'membership-freeze',title:'Membership pause & freeze request',description:'A member has asked to pause or freeze their membership. Log the dates and reason for Accounts.',category:'Pricing and Memberships',subcategory:'Membership Pause and Freeze Policy',kind:'request',featured:true,icon:'pause',fields:[{id:'freezeFrom',label:'Freeze from',type:'datetime-local',required:true},{id:'freezeUntil',label:'Return date',type:'datetime-local',required:true},select('reason','Reason given',['Travel','Medical recovery','Personal circumstances','Other'])]},
{id:'hosted-class-feedback',title:'Hosted / community class feedback',description:'Log a partner-hosted or community class — attendance, host feedback and whether it converted.',category:'Brand Feedback',subcategory:'Collaborations and Partnerships',kind:'feedback',featured:true,icon:'users',provenance:attribution,classContext:true,fields:[select('classType','Class format',CLASS_FORMATS,true,'Hosted and community sessions are usually logged as "Studio Hosted Class".'),{id:'partnerName',label:'Partner / host name',type:'text',required:true},select('sessionStatus','Overall hosted session status',['Excellent flow','Good with minor fixes','Mixed / needs follow-up','Disrupted','Cancelled']),select('acquisitionSource','How attendees found the class',['Partner referral','Instagram / social','Existing member guest','Corporate community','Walk-in / invite','Other']),text('attendeeFeedback','What attendees said',true,'Summarise reactions in the room, quoting anyone specific.'),text('attendeeHighlights','Attendee-level notes',false,'Capture notable attendee statuses, comments, package interest and follow-up details.'),select('hostFeedback','Feedback on the host',['Strong satisfaction','Mixed feedback','Wants another collaboration','Requested changes first','Not captured']),select('lateArrivals','Late arrivals',['None','1–2','3+','Affected the class flow','Unknown']),select('conversion','Purchase intent seen in the room',['Strong package interest','Intro offer interest','Needs nurturing','Package sold on the day','Low intent']),select('audienceFit','Audience fit for Physique 57',['Strong fit','Good fit with nurturing','Mixed audience','Proximity issue']),select('collaborateAgain','Would you run this again?',['Definitely','Maybe','No','Needs management review'])]},
{id:'instructor-late-for-class',title:'Instructor was late to class',description:'A trainer started late or wasn\u2019t on the floor on time — capture the exact timing and how it was handled.',category:'Trainer Feedback',subcategory:'Trainer Punctuality Issues',kind:'issue',featured:true,icon:'clock',provenance:attribution,classContext:true,fields:[{id:'actualStartTime',label:'Actual start time',type:'datetime-local',required:true},{id:'arrivalTime',label:'Instructor arrival time',type:'datetime-local',required:true},{id:'delayMinutes',label:'Delay, in minutes',type:'number',required:true},select('advanceNotice','Did the instructor give notice?',['Before scheduled start','After scheduled start','No advance notice','Unable to confirm']),text('reason','Reason given for the delay',false),select('membersAffected','Members affected',['One member','2–5 members','6+ members','Full class','Unknown']),text('recoveryOffered','Recovery already offered to members',false,'Credit, apology, reschedule — note anything already done.')]},
{id:'late-arrival-entry-denied',title:'Member arrived late, entry denied',description:'A member was turned away for arriving after the cut-off. Log the timing and how the policy was applied.',category:'Scheduling',subcategory:'Late Arrival Policy',kind:'issue',featured:true,icon:'door',provenance:attribution,classContext:true,fields:[{id:'arrivalTime',label:'Member arrival time',type:'datetime-local',required:true},text('denialReason','Reason entry was denied',true),select('policyCommunicated','Was the late-arrival policy shared in advance?',['Yes','No','Unable to confirm']),select('policyChannel','Where was it shared?',['WhatsApp','Email','Phone','Front desk','App','Unknown']),select('recovery','Was the class recovered for the member?',['Credit restored','Rescheduled','Both','Neither yet','Review pending'])]},
{id:'member-class-experience',title:'Member shared feedback on a class',description:'A member told you (or you noticed) something about a class — format, pacing, instructor or environment.',category:'Class Experience',subcategory:'Class Format Satisfaction',kind:'feedback',featured:true,icon:'sparkles',provenance:attribution,classContext:true,fields:[select('practiceElement','What part of the class stood out',['Format','Instructor','Music / audio','Pacing','Intensity','Modifications offered','Studio environment','Timing']),select('satisfaction','Member sentiment',['Delighted','Satisfied','Mixed','Dissatisfied','Frustrated']),text('requestedChange','Anything they asked to change',false)]},
{id:'studio-environment',title:'Studio environment issue',description:'Something in the studio needs attention — temperature, cleanliness, noise, smell or a facilities snag.',category:'Studio Amenities and Facilities',subcategory:'Cleanliness and Hygiene',kind:'issue',featured:true,icon:'building',provenance:attribution,fields:[select('area','Where in the studio',STUDIO_AREAS,true),select('element','What kind of issue',['Temperature / AC','Lighting','Sound','Cleanliness','Odour','Toiletries / towels','Showers / lockers','Equipment spacing']),text('reportedImpact','How it affected the floor or members',true),text('immediateAction','Immediate action already taken',false)]},
{id:'tech-system-fault',title:'System or equipment fault',description:'Momence, POS, Wi-Fi, mic, iPad or any studio system misbehaving — log it so Ops can chase it down.',category:'Tech Issues',subcategory:'App Performance Bugs',kind:'issue',featured:true,icon:'building',fields:[select('systemName','Which system',SYSTEMS,true),select('occurredWhen','When did this happen',OCCURRED_OPTIONS),text('errorDetail','What exactly happened',true,'Error message, screen it froze on, what you tried already.'),select('classImpact','Is it blocking a class or booking right now?',['Yes, blocking now','Not yet, but it will be','No, comfort / back-office only'])]},
{id:'powercycle-bike-fault',title:'PowerCycle bike malfunction',description:'A bike is faulty — resistance knob, pedal, flywheel, console or noise. A 48-hour relapse check is auto-scheduled once this is resolved.',category:'Repair and Maintenance',subcategory:'Broken Equipment Not Repaired',kind:'issue',featured:true,icon:'building',fields:[num('bikeNumber','Bike number, if labelled',false),select('faultType','Type of fault',['Resistance knob stuck','Pedal / strap issue','Flywheel noise','Console / display not working','Seat or handlebar loose','Other']),select('classImpact','Is it blocking a class right now?',['Yes, blocking now','Not yet, but it will be','No, comfort / back-office only']),text('errorDetail','Describe exactly what\u2019s wrong',true),text('immediateAction','Immediate action taken (e.g. bike taken out of rotation)',false)]},
{id:'member-compliment',title:'A moment worth celebrating',description:'Log a compliment or a great moment a member shared. No SLA, no resolution — just a record for the team.',category:'Class Experience',subcategory:'Instructor Energy and Motivation',kind:'compliment',featured:true,icon:'heart',classContext:true,fields:[select('recognition','Who deserves the recognition?',['Instructor','Front desk','Studio team','Overall experience']),text('highlight','What made the difference',false)]},
{id:'safety-incident',title:'Safety or security incident',description:'Anything from a blocked exit to a harassment report — logged discreetly and escalated immediately.',category:'Safety and Security',subcategory:'Personal Safety Concerns',kind:'issue',featured:true,icon:'shield',fields:[select('isImmediateDanger','Is anyone in immediate danger right now?',['Yes — happening now','No, but it needs urgent attention'],true),select('alreadyReported','Has this already been flagged to a manager or security?',['Yes','Not yet']),text('narrative','Exactly what happened',true),text('witnesses','Anyone else who witnessed this',false)]},
{id:'theft-report',title:'Theft or missing item report',description:'A member or staff item has gone missing. Log the description and last-seen location for the investigation.',category:'Theft and Lost Items',subcategory:'Locker Theft',kind:'issue',featured:true,icon:'building',fields:[text('itemDescription','What item is missing?',true,'Brand, colour, distinguishing marks.'),select('lastSeen','Where was it last seen?',['Locker','Studio floor','Lounge','Valet','Boutique','Changing room']),select('occurredWhen','When did this happen?',OCCURRED_OPTIONS),text('requestedResolution','What needs to happen next?',false)]},
{id:'billing-dispute',title:'Billing or charge dispute',description:'A member has flagged an unexpected or incorrect charge. Capture the transaction detail for Accounts.',category:'Pricing and Memberships',subcategory:'Refund and Cancellation Policy Issue',kind:'issue',featured:true,icon:'building',fields:[select('membershipRef','Membership / package',MEMBERSHIPS,false),num('amount','Amount involved (₹)',true),text('transactionRef','Transaction / invoice reference',false),text('narrative','What the member is disputing',true)]},
...(['PowerCycle','Strength / FIT','Barre','Non-technical'] as const).map((name,i):GuidedTemplate=>({id:'trainer-assessment-'+i,title:name+' trainer assessment',description:'Internal weighted evaluation, coaching observations and a development plan for a trainer.',category:'Trainer Feedback',subcategory:'Knowledge and Competence',kind:'assessment',featured:i<2,icon:'clipboard',provenance:attribution,fields:[{id:'evaluator',label:'Evaluator name',type:'text',required:true},...rubric('rating',i===0?powerCycle:i===1?strength:i===2?barre:[['Overall class experience',5]]),text('strengths','Key strengths observed'),text('improvements','Development areas'),text('coachingPlan','Coaching action plan')]})),
];

export function guidedTemplates():GuidedTemplate[]{
  const specialKeys=new Set(SPECIAL_TEMPLATES.map(t=>t.category+'::'+t.subcategory));
  return [...SPECIAL_TEMPLATES,...Object.entries(CATEGORY_MAP).flatMap(([category,subs])=>subs.filter(sub=>!specialKeys.has(category+'::'+sub)).map((subcategory):GuidedTemplate=>({id:slugify(category+'-'+subcategory),title:subcategory,description:`A guided, ready-to-submit ${category.toLowerCase()} report with fields tailored to ${subcategory.toLowerCase()}.`,category,subcategory,kind:'issue',icon:'ticket',classContext:['Scheduling','Class Experience','Trainer Feedback'].includes(category),fields:defaultFieldsForCategory(category)})))];
}
export function scoreAssessment(fields:StructuredField[],values:Record<string,unknown>){const rubric=fields.filter(f=>f.type==='rating'&&f.weight);const total=rubric.reduce((n,f)=>n+(f.weight||0),0);if(!total)return null;return Math.round(rubric.reduce((n,f)=>n+Number(values[f.id]||0)/5*(f.weight||0),0)/total*100);}
