import {lookup} from 'dns/promises';import {createHash} from 'crypto';import {and,eq,desc,sql} from 'drizzle-orm';import {z} from 'zod';
import {db} from '@/db';import {integrations,deliveryLogs} from '@/db/schema';import {credentials,audit} from './config';import {ApiError} from './auth';import {getAccessToken,obj} from './momence';import {INTEGRATION_CATALOGUE} from './integration-catalogue';
function required(v:unknown,label:string){if(v===undefined||v===null||String(v).trim()==='')throw new ApiError(`${label} is required.`);return String(v);}
function identifier(v:unknown,label:string){const id=required(v,label);if(!/^[\w.-]+$/.test(id))throw new ApiError(`${label} has invalid characters.`);return encodeURIComponent(id);}
export function redacted(data:unknown):unknown{if(Array.isArray(data))return data.slice(0,100).map(redacted);if(data&&typeof data==='object')return Object.fromEntries(Object.entries(data).map(([k,v])=>[k,/(token|secret|password|api_key|authorization)/i.test(k)?'[redacted]':redacted(v)]));return data;}
async function remote(url:string,token:string,method='GET',body?:unknown,headers:Record<string,string>={}){const res=await fetch(url,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(25000),redirect:'error',cache:'no-store'});if(!res.ok){let detail='';try{const r=obj(await res.json());detail=String(obj(r.error).message||r.message||r.error_description||'');}catch{}throw new ApiError(`Provider returned ${res.status}${detail?': '+detail.slice(0,250):'. Check credentials, permissions and payload.'}`,502);}const text=await res.text();if(!text)return{success:true};try{return JSON.parse(text);}catch{return{response:text.slice(0,10000)};}}
async function publicWebhook(raw:string){const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password)throw new ApiError('Use a public HTTPS webhook without credentials in the URL.');const records=await lookup(u.hostname,{all:true});if(!records.length||records.some(({address})=>/^(0\.|10\.|127\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.|::|f[cd]|fe80)/i.test(address)||address.includes('::ffff:')))throw new ApiError('Internal and reserved network addresses are not allowed.');return u.toString();}
async function sendMailtrap(c:Record<string,string>,b:{to:{email:string}[];subject:string;text:string;html?:string}){
  if(c.smtp_host&&c.smtp_username&&c.smtp_password){
    const nodemailer=(await import('nodemailer')).default;
    const transport=nodemailer.createTransport({host:c.smtp_host,port:Number(c.smtp_port)||587,secure:Number(c.smtp_port)===465,auth:{user:c.smtp_username,pass:c.smtp_password}});
    const info=await transport.sendMail({from:`"Physique 57 India" <${c.from_email}>`,to:b.to.map(t=>t.email).join(','),subject:b.subject,text:b.text,html:b.html});
    return{messageId:info.messageId,accepted:info.accepted,via:'smtp'};
  }
  if(c.api_key)return{...(await remote('https://send.api.mailtrap.io/api/send',c.api_key,'POST',{from:{email:c.from_email,name:'Physique 57 India'},...b,category:'IRIS operations'})),via:'api'};
  throw new ApiError('Provide either an API token or full SMTP credentials for Mailtrap.');
}
const googleCache=new Map<string,{fingerprint:string;token:string;expires:number}>();
async function googleToken(id:string){const c={...await credentials('google'),...await credentials(id)};if(c.access_token)return c.access_token;required(c.client_id,'Google client ID');required(c.client_secret,'Google client secret');required(c.refresh_token,'Google refresh token');const fingerprint=createHash('sha256').update(c.client_id+c.client_secret+c.refresh_token).digest('hex');const cached=googleCache.get(id);if(cached?.fingerprint===fingerprint&&cached.expires>Date.now()+60000)return cached.token;const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:c.client_id,client_secret:c.client_secret,refresh_token:c.refresh_token}),signal:AbortSignal.timeout(20000)});if(!res.ok)throw new ApiError('Google token refresh failed. Check OAuth credentials and granted scopes.',502);const j=obj(await res.json());const token=required(j.access_token,'Google access token');googleCache.set(id,{fingerprint,token,expires:Date.now()+Number(j.expires_in||3600)*1000});return token;}
export async function runIntegration(id:string,action:string,args:Record<string,unknown>={}):Promise<unknown>{const c=await credentials(id);if(action!=='test'&&c._enabled==='false')throw new ApiError('This integration is disabled. Enable it before running actions.',409);if(id==='momence'){await getAccessToken(true);return{authenticated:true,token:'[server-side only]'};}
if(id==='chatgpt')return remote('https://api.openai.com/v1/models',required(c.api_key,'OpenAI API key'));
if(id==='n8n'){const url=await publicWebhook(required(c.webhook_url,'n8n production webhook URL'));if(action==='test')return{configurationValid:true,message:'Webhook URL is valid. Use Trigger a workflow to verify delivery with an explicit confirmed test event.'};return remote(url,'','POST',args,{'X-Webhook-Secret':required(c.webhook_secret,'Webhook secret'),'X-IRIS-Event-Id':String(args.eventId||crypto.randomUUID())});}
if(id==='mailtrap'){required(c.from_email,'Verified sender email');if(action==='test')return{configurationValid:Boolean(c.api_key||(c.smtp_host&&c.smtp_username&&c.smtp_password)),message:'Saved. Mailtrap delivery is verified only by an explicit send to your selected recipient.'};const b=z.object({to:z.array(z.object({email:z.string().email()})).min(1).max(20),subject:z.string().min(1).max(200),text:z.string().min(1).max(50000),html:z.string().max(200000).optional()}).parse(args);return sendMailtrap(c,b);}
if(id==='whatsapp'){const token=required(c.access_token,'Meta access token');const version=c.api_version||'v23.0';if(!/^v\d+\.\d+$/.test(version))throw new ApiError('Invalid Graph API version');const phone=identifier(c.phone_number_id,'Business phone number ID');if(action==='test')return remote(`https://graph.facebook.com/${version}/${phone}?fields=display_phone_number,verified_name`,token);required(args.to,'Recipient number');if(!['text','template'].includes(String(args.type)))throw new ApiError('Message type must be text or template.');return remote(`https://graph.facebook.com/${version}/${phone}/messages`,token,'POST',{...args,messaging_product:'whatsapp'});}
if(id==='fillout'){const token=required(c.api_key,'Fillout API key');if(action==='test'||action==='forms')return remote('https://api.fillout.com/v1/api/forms',token);const formId=identifier(args.formId||c.form_id,'Form ID');if(action==='submissions')return remote(`https://api.fillout.com/v1/api/forms/${formId}/submissions?limit=20&offset=${Math.max(0,Number(args.offset)||0)}`,token);const submissionId=identifier(args.submissionId,'Exact submission ID');const submission=await remote(`https://api.fillout.com/v1/api/forms/${formId}/submissions/${submissionId}`,token);if(action==='import'){const {importFillout}=await import('./fillout');return importFillout({formId,submission,submissionId,templateId:args.templateId});}return submission;}
if(id==='respond'){const token=required(c.api_key,'respond.io API token');if(action==='test'||action==='channels')return remote('https://api.respond.io/v2/space/channel',token);const contact=required(args.identifier,'Contact identifier');if(!/^(id|email|phone):.+$/.test(contact))throw new ApiError('Use an id:, email: or phone: contact identifier.');const url='https://api.respond.io/v2/contact/'+encodeURIComponent(contact);if(action==='contact')return remote(url,token);return remote(url+'/message',token,'POST',{channelId:args.channelId,message:args.message});}
if(id==='gmail'||id.startsWith('google-')){const token=await googleToken(id);if(action==='test')return{authenticated:true,message:'Google OAuth token refreshed. Use a read action to verify this API’s scopes.'};if(id==='gmail'){if(action==='messages')return remote('https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=20',token);const b=z.object({to:z.string().email(),subject:z.string().min(1).max(200).refine(s=>!/[\r\n]/.test(s)),text:z.string().min(1).max(50000)}).parse(args);const raw=Buffer.from(`To: ${b.to}\r\nSubject: =?UTF-8?B?${Buffer.from(b.subject).toString('base64')}?=\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${b.text}`).toString('base64url');return remote('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',token,'POST',{raw});}
if(id==='google-calendar'){const cal=encodeURIComponent(c.calendar_id||'primary');const url=`https://www.googleapis.com/calendar/v3/calendars/${cal}/events`;if(action==='events')return remote(url+'?maxResults=25&singleEvents=true&orderBy=startTime&timeMin='+encodeURIComponent(new Date().toISOString()),token);if(!args.start||!args.end||!args.summary)throw new ApiError('Event summary, start and end are required.');return remote(url+'?sendUpdates=none',token,'POST',args);}
if(id==='google-contacts'){if(action==='contacts')return remote('https://people.googleapis.com/v1/people/me/connections?personFields=names,emailAddresses,phoneNumbers&pageSize=100',token);if(!Array.isArray(args.names))throw new ApiError('Contact names are required');return remote('https://people.googleapis.com/v1/people:createContact',token,'POST',args);}
if(id==='google-sheets'){const sheet=identifier(args.spreadsheetId||c.spreadsheet_id,'Spreadsheet ID'),range=encodeURIComponent(String(args.range||c.range||'Sheet1!A:Z'));const url=`https://sheets.googleapis.com/v4/spreadsheets/${sheet}/values/${range}`;if(action==='read')return remote(url,token);const values=z.array(z.array(z.union([z.string(),z.number(),z.boolean(),z.null()]))).max(1000).parse(args.values);return remote(url+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS',token,'POST',{values});}
if(id==='google-docs'){if(action==='create')return remote('https://docs.googleapis.com/v1/documents',token,'POST',{title:required(args.title,'Document title')});const doc=identifier(args.documentId||c.document_id,'Document ID');if(action==='read')return remote('https://docs.googleapis.com/v1/documents/'+doc,token);if(!Array.isArray(args.requests))throw new ApiError('Document update requests are required.');return remote('https://docs.googleapis.com/v1/documents/'+doc+':batchUpdate',token,'POST',{requests:args.requests});}}
if(id==='slack'||id==='discord'||id==='teams'){const url=await publicWebhook(required(c.webhook_url,'Webhook URL'));if(action==='test')return{configurationValid:true,message:'Webhook URL saved. Use Post a message to verify delivery.'};return remote(url,'','POST',args);}
if(id==='zapier'){const url=await publicWebhook(required(c.webhook_url,'Zapier catch hook URL'));if(action==='test')return{configurationValid:true};return remote(url,'','POST',args);}
if(id==='notion'){const token=required(c.api_key,'Notion internal integration token');const headers={'Notion-Version':'2022-06-28'};if(action==='test')return remote('https://api.notion.com/v1/users/me',token,'GET',undefined,headers);return remote('https://api.notion.com/v1/pages',token,'POST',{parent:{database_id:required(c.database_id,'Database ID')},...args},headers);}
if(id==='airtable'){const token=required(c.api_key,'Airtable personal access token');const base=identifier(c.base_id,'Base ID');const table=encodeURIComponent(required(c.table_name,'Table name'));const url=`https://api.airtable.com/v0/${base}/${table}`;if(action==='test')return remote(url+'?maxRecords=1',token);return remote(url,token,'POST',args);}
if(id==='trello'){const key=required(c.api_key,'Trello API key');const token=required(c.token,'Trello token');const qs=`key=${encodeURIComponent(key)}&token=${encodeURIComponent(token)}`;if(action==='test')return remote(`https://api.trello.com/1/members/me?${qs}`,'');return remote(`https://api.trello.com/1/cards?idList=${identifier(c.list_id,'List ID')}&${qs}`,'','POST',args);}
if(id==='asana'){const token=required(c.api_key,'Asana personal access token');if(action==='test')return remote('https://app.asana.com/api/1.0/users/me',token);return remote('https://app.asana.com/api/1.0/tasks',token,'POST',{data:{...obj(args),projects:c.project_id?[c.project_id]:[]}});}
if(id==='zendesk'){const sub=required(c.subdomain,'Zendesk subdomain');const auth='Basic '+Buffer.from(`${required(c.email,'Agent email')}/token:${required(c.api_token,'API token')}`).toString('base64');if(action==='test')return remote(`https://${sub}.zendesk.com/api/v2/users/me.json`,'','GET',undefined,{Authorization:auth});return remote(`https://${sub}.zendesk.com/api/v2/tickets.json`,'','POST',{ticket:args},{Authorization:auth});}
if(id==='twilio'){const sid=required(c.account_sid,'Account SID');const authHeader='Basic '+Buffer.from(`${sid}:${required(c.auth_token,'Auth token')}`).toString('base64');const form=new URLSearchParams({To:required(args.to,'Recipient number'),From:required(c.from_number,'Sending number'),Body:required(args.body,'Message body')});const res=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:authHeader,'Content-Type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(20000)});if(!res.ok)throw new ApiError('Twilio returned '+res.status);return res.json();}
if(id==='hubspot'){const token=required(c.api_key,'HubSpot private app token');if(action==='test')return remote('https://api.hubapi.com/crm/v3/objects/tickets?limit=1',token);return remote('https://api.hubapi.com/crm/v3/objects/tickets',token,'POST',args);}
if(id==='calendly'){const token=required(c.api_key,'Calendly personal access token');return remote('https://api.calendly.com/event_types',token);}
if(id==='stripe'){const key=required(c.api_key,'Stripe secret key');const auth='Basic '+Buffer.from(key+':').toString('base64');if(action==='test')return remote('https://api.stripe.com/v1/balance','','GET',undefined,{Authorization:auth});return remote('https://api.stripe.com/v1/customers/'+identifier(args.customerId,'Customer ID'),'','GET',undefined,{Authorization:auth});}
if(id==='razorpay'){const auth='Basic '+Buffer.from(`${required(c.key_id,'Key ID')}:${required(c.key_secret,'Key secret')}`).toString('base64');if(action==='test')return remote('https://api.razorpay.com/v1/payments?count=1','','GET',undefined,{Authorization:auth});return remote('https://api.razorpay.com/v1/payments/'+identifier(args.paymentId,'Payment ID'),'','GET',undefined,{Authorization:auth});}
if(id==='jira'){const site=required(c.site,'Jira site');const auth='Basic '+Buffer.from(`${required(c.email,'Account email')}:${required(c.api_token,'API token')}`).toString('base64');if(action==='test')return remote(`https://${site}/rest/api/3/myself`,'','GET',undefined,{Authorization:auth});return remote(`https://${site}/rest/api/3/issue`,'','POST',{fields:{project:{key:c.project_key},...obj(args).fields as object}},{Authorization:auth});}
throw new ApiError('Unknown integration action.');}
export async function loggedIntegration(id:string,action:string,args:Record<string,unknown>,actor:{id?:number;name:string}){const[entry]=await db.insert(deliveryLogs).values({integrationId:id,action,status:'sending',payload:redacted(args) as Record<string,unknown>,attempts:1}).returning();try{const result=await runIntegration(id,action,args);await db.update(deliveryLogs).set({status:'success',result:{data:redacted(result)},updatedAt:new Date()}).where(eq(deliveryLogs.id,entry.id));await audit(actor,'integration.executed',id,{action,deliveryId:entry.id});return result;}catch(e){await db.update(deliveryLogs).set({status:'failed',result:{error:e instanceof Error?e.message:'Provider unavailable'},updatedAt:new Date()}).where(eq(deliveryLogs.id,entry.id));throw e;}}
export async function deliverPending(){const pending=await db.select().from(deliveryLogs).where(eq(deliveryLogs.status,'pending')).limit(10);for(const job of pending){const[claimed]=await db.update(deliveryLogs).set({status:'sending',attempts:sql`${deliveryLogs.attempts}+1`,updatedAt:new Date()}).where(and(eq(deliveryLogs.id,job.id),eq(deliveryLogs.status,'pending'))).returning();if(!claimed)continue;try{const[connection]=await db.select().from(integrations).where(eq(integrations.id,job.integrationId));if(!connection?.enabled)throw new Error('Integration disabled. Enable it before retrying.');const result=await runIntegration(job.integrationId,job.action,{...job.payload,eventId:'iris-delivery-'+job.id});await db.update(deliveryLogs).set({status:'success',result:{data:redacted(result)},updatedAt:new Date()}).where(eq(deliveryLogs.id,job.id));}catch(e){await db.update(deliveryLogs).set({status:'failed',result:{error:e instanceof Error?e.message:'Delivery failed'},updatedAt:new Date()}).where(eq(deliveryLogs.id,job.id));}}return{processed:pending.length};}
