import {credentials,audit} from './config';
import {ApiError} from './auth';
import {CLASS_FORMATS,MEMBERSHIPS,STUDIOS,TRAINERS} from './constants';
import catalogue from './momence-catalogue.json';
export type JsonRecord=Record<string,unknown>;
export type MomenceRecord={id:string;name:string;subtitle:string;kind:string;raw:JsonRecord};
export type ModuleName='members'|'sessions'|'memberships'|'studios'|'sales';
export const obj=(v:unknown):JsonRecord=>v&&typeof v==='object'&&!Array.isArray(v)?v as JsonRecord:{};
export const arr=(v:unknown):JsonRecord[]=>Array.isArray(v)?v.map(obj):[];
export function value(v:unknown):string{if(v===null||v===undefined)return '—';if(typeof v==='object'){const r=obj(v);return String(r.name||[r.firstName,r.lastName].filter(Boolean).join(' ')||r.label||r.id||'');}return String(v);}
export function payload(v:unknown):JsonRecord[]{if(Array.isArray(v))return arr(v);const r=obj(v);return arr(r.payload??r.responses??r.items??r.data);}
let tokenCache:{fingerprint:string;token:string;refresh:string;expires:number}|undefined;
let tokenPromise:Promise<string>|undefined;
export async function momenceConfigured(){const c=await credentials('momence');return c._enabled!=='false'&&Boolean(c.username&&c.password&&c.client_id&&c.client_secret||c.access_token);}
async function acquireToken(force=false){const c=await credentials('momence');if(c.username&&c.password&&c.client_id&&c.client_secret){const fingerprint=JSON.stringify([c.username,c.password,c.client_id,c.client_secret]);if(!force&&tokenCache?.fingerprint===fingerprint&&tokenCache.expires>Date.now()+60000)return tokenCache.token;
const auth='Basic '+Buffer.from(c.client_id+':'+c.client_secret).toString('base64');
const exchange=async(refresh?:string)=>{const body=new URLSearchParams(refresh?{grant_type:'refresh_token',refresh_token:refresh}:{grant_type:'password',username:c.username,password:c.password});return fetch('https://api.momence.com/api/v2/auth/token',{method:'POST',headers:{Authorization:auth,'Content-Type':'application/x-www-form-urlencoded'},body,signal:AbortSignal.timeout(20000),cache:'no-store'});};
let res=await exchange(tokenCache?.fingerprint===fingerprint?tokenCache.refresh:undefined);if(!res.ok&&tokenCache?.refresh)res=await exchange();if(!res.ok)throw new ApiError(`Momence authentication failed (${res.status}). Check username, password and API client credentials.`,502);const j=obj(await res.json());const token=String(j.access_token||j.accessToken||'');if(!token)throw new ApiError('Momence did not return an access token.',502);const expiry=Date.parse(String(j.accessTokenExpiresAt||''));tokenCache={fingerprint,token,refresh:String(j.refresh_token||j.refreshToken||''),expires:Number.isFinite(expiry)?expiry:Date.now()+3000000};return token;}
if(c.access_token)return c.access_token;throw new ApiError('Connect Momence using your username, password, client ID and client secret in Settings → Integrations.',503);}
export async function getAccessToken(force=false){if(force)tokenCache=undefined;if(!tokenPromise)tokenPromise=acquireToken(force).finally(()=>{tokenPromise=undefined;});return tokenPromise;}
export async function momenceRequest(path:string,method='GET',body?:unknown){const token=await getAccessToken();const perform=(t:string)=>fetch('https://api.momence.com'+path,{method,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',Accept:'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(25000)});let res=await perform(token);if(res.status===401)res=await perform(await getAccessToken(true));if(!res.ok){const raw=await res.text();let message='';try{message=value(obj(JSON.parse(raw)).message);}catch{}throw new ApiError(`Momence returned ${res.status}${message&&message!=='—'?': '+message.slice(0,200):'. Please check permissions and parameters.'}`,502);}if(res.status===204)return{};const text=await res.text();return text?JSON.parse(text):{};}
function normalise(kind:string,r:JsonRecord):MomenceRecord {let name=value(r.name);let subtitle='';if(kind==='members'){name=[r.firstName,r.lastName].filter(Boolean).join(' ');subtitle=String(r.email||'');}if(kind==='sessions'){subtitle=[value(r.teacher),value(r.inPersonLocation)].filter(v=>v!=='—').join(' · ');}if(kind==='memberships'){name=value(r.name||obj(r.membership).name);subtitle=value(r.type);}if(kind==='sales'){name='Sale #'+r.id;subtitle=value(r.saleDate);}if(kind==='studios')subtitle=value(r.city);return{id:String(r.id),name:name==='—'?kind+' #'+r.id:name,subtitle,kind,raw:r};}
function demoData(module:string):JsonRecord[]{if(module==='studios')return STUDIOS.map((s,i)=>({id:i+1,name:s.name,city:s.city,address:s.address,source:'Workspace directory; not verified Momence IDs'}));if(module==='members')return [['Priya','Mehta','Kwality House, Kemps Corner'],['Aarav','Khanna','Supreme HQ, Bandra'],['Ananya','Rao','Kenkere House, Bengaluru'],['Meher','Daruwalla','Courtside, Mumbai'],['Kabir','Menon',STUDIOS[4].name],['Sana','Kapoor',STUDIOS[0].name]].map(([firstName,lastName,studio],i)=>({id:481102+i,firstName,lastName,email:`${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,phoneNumber:null,visits:{totalVisits:24+i*17,bookings:30+i*18},homeLocation:studio,customerTags:[{name:i%2?'Class pack':'Unlimited'}],firstSeen:'2025-01-12T00:00:00Z',lastSeen:new Date(Date.now()-i*86400000).toISOString()}));if(module==='sessions')return [...CLASS_FORMATS,...CLASS_FORMATS].map((name,i)=>({id:2200+i,name,type:'fitness',description:'A focused, full-body studio experience. Sample session for exploring IRIS.',startsAt:new Date(Date.now()+(i-8)*4*3600000).toISOString(),endsAt:new Date(Date.now()+(i-8)*4*3600000+57*60000).toISOString(),durationInMinutes:57,capacity:24,bookingCount:12+i%13,isCancelled:i===8,isInPerson:true,isRecurring:true,isDraft:false,teacher:{id:i+1,firstName:TRAINERS[i%TRAINERS.length].split(' ')[0],lastName:TRAINERS[i%TRAINERS.length].split(' ').slice(1).join(' ')},inPersonLocation:{id:i%5+1,name:STUDIOS[i%5].name}}));if(module==='memberships')return MEMBERSHIPS.map((name,i)=>({id:100+i,name,type:name.toLowerCase().includes('unlimited')?'subscription':'package-events',description:'Configured Physique 57 package. Prices are only available after a live connection.',isDisabled:false}));return[];}
export type SessionFilters={sessionTypes?:string[];upcoming?:boolean};
/** Maps a workspace studio name to its live Momence location id. Two studios have no Momence
 *  location, so they return undefined and the caller leaves the listing unfiltered. */
export function momenceLocationFor(studio?:string|null):number|undefined{if(!studio)return undefined;const hit=STUDIOS.find(s=>s.name===studio);return hit?.momenceLocationId??undefined;}
export async function listMomence(module:ModuleName,params:{query?:string;page?:number;pageSize?:number;startAfter?:string;startBefore?:string;locationId?:string}&SessionFilters={}){const configured=await momenceConfigured();const page=params.page||0,pageSize=params.pageSize||24;if(module==='studios'||!configured){let items=demoData(module);if(params.query)items=items.filter(r=>JSON.stringify(r).toLowerCase().includes(params.query!.toLowerCase()));if(module==='sessions'){if(params.startAfter)items=items.filter(r=>String(r.startsAt)>=params.startAfter!);const before=params.startBefore||(params.upcoming?undefined:new Date().toISOString());if(before)items=items.filter(r=>String(r.startsAt)<=before);items=items.sort((a,b)=>String(b.startsAt).localeCompare(String(a.startsAt)));}return{items:items.slice(page*pageSize,(page+1)*pageSize).map(r=>normalise(module,r)),source:module==='studios'?'workspace':'demo',total:items.length,page,hasMore:(page+1)*pageSize<items.length};}
const qs=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(module==='members'&&params.query)qs.set('query',params.query);if(module==='sessions'){qs.set('includeCancelled','true');
// Momence defaults to oldest-first, which buries every recent class behind a decade of history.
// Newest first, and by default no classes that have not happened yet.
qs.set('sortBy','startsAt');qs.set('sortOrder','DESC');
if(params.startAfter)qs.set('startAfter',params.startAfter);
if(params.startBefore)qs.set('startBefore',params.startBefore);
else if(!params.upcoming)qs.set('startBefore',new Date().toISOString());
if(params.locationId)qs.set('locationId',params.locationId);
// `types` is an array parameter: Momence rejects a bare `types=private` with "types must be an array".
for(const t of params.sessionTypes||[])qs.append('types[]',t);}const result=obj(await momenceRequest(`/api/v2/host/${module}?${qs}`));let rows=payload(result);if(module!=='members'&&params.query)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(params.query!.toLowerCase()));const p=obj(result.pagination);return{items:rows.map(r=>normalise(module,r)),source:'live',total:typeof p.total=== 'number'?p.total:typeof p.totalCount==='number'?p.totalCount:null,page,hasMore:payload(result).length===pageSize};}
export async function detailMomence(module:ModuleName,id:string,page=0){if(!/^\d+$/.test(id))throw new ApiError('Invalid record ID');const live=await momenceConfigured();if(!live||module==='studios'){const raw=demoData(module).find(x=>String(x.id)===id);if(!raw)throw new ApiError('Record not found',404);const related:Record<string,JsonRecord[]>={};if(module==='members'){related.memberships=[{id:110,name:MEMBERSHIPS[18],membership:{id:118,name:MEMBERSHIPS[18]},type:'subscription',isFrozen:false,startDate:'2026-01-01',endDate:'2026-12-31'}];related.bookings=[{id:901,checkedIn:true,cancelledAt:null,session:demoData('sessions')[10]}];related.notes=[{id:1,type:'regular',note:'Sample note: prefers morning classes. Demo data only.',createdAt:new Date().toISOString()}];}if(module==='sessions'){related.bookings=demoData('members').map((m,i)=>({id:901+i,member:m,checkedIn:i<3,cancelledAt:i===5?new Date().toISOString():null,createdAt:new Date().toISOString(),ticketsBought:1}));}return{item:normalise(module,raw),related,source:module==='studios'?'workspace':'demo',page,hasMore:false,errors:[] as string[]};}
let raw:JsonRecord;const related:Record<string,JsonRecord[]>={};const errors:string[]=[];if(module==='members'||module==='sessions')raw=obj(await momenceRequest(`/api/v2/host/${module}/${id}`));else{const rows=await listMomence(module,{pageSize:100,page});const found=rows.items.find(r=>r.id===id);if(!found)throw new ApiError('Record not found on this page',404);raw=found.raw;}
const routes:Record<string,string>=module==='members'?{memberships:`/members/${id}/bought-memberships/active`,bookings:`/members/${id}/sessions`,notes:`/members/${id}/notes`}:module==='sessions'?{bookings:`/sessions/${id}/bookings`}:{};
await Promise.all(Object.entries(routes).map(async([key,path])=>{try{const qs=new URLSearchParams({page:String(page),pageSize:'50'});if(key==='bookings')qs.set('includeCancelled','true');if(key==='memberships')qs.set('includeFrozen','true');related[key]=payload(await momenceRequest(`/api/v2/host${path}?${qs}`));}catch(e){errors.push(`${key}: ${e instanceof Error?e.message:'Unavailable'}`);related[key]=[];}}));return{item:normalise(module,raw),related,errors,source:'live',page,hasMore:Object.values(related).some(r=>r.length===50)};}
export function validateBody(schema:unknown,input:unknown,label='body'):void{const s=obj(schema);if(s.nullable&&input===null)return;if(s.oneOf){const candidates=arr(s.oneOf);if(!candidates.some(c=>{try{validateBody(c,input,label);return true;}catch{return false;}}))throw new ApiError(`${label} does not match the documented request.`);return;}if(s.allOf)for(const c of arr(s.allOf))validateBody(c,input,label);if(s.type==='object'){if(input===null||typeof input!=='object'||Array.isArray(input))throw new ApiError(`${label} must be an object.`);const r=obj(input);for(const key of (s.required||[]) as string[])if(!(key in r))throw new ApiError(`${label}.${key} is required.`);for(const[k,v]of Object.entries(r)){const def=obj(s.properties)[k];if(def)validateBody(def,v,label+'.'+k);}}if(s.type==='array'){if(!Array.isArray(input))throw new ApiError(`${label} must be an array.`);for(const v of input)validateBody(s.items,v,label+'[]');}if(['string','boolean','number','integer'].includes(String(s.type))){const expected=s.type==='integer'?'number':s.type;if(typeof input!==expected)throw new ApiError(`${label} must be ${s.type}.`);if(s.type==='integer'&&!Number.isInteger(input))throw new ApiError(`${label} must be an integer.`);}if(Array.isArray(s.enum)&&!s.enum.includes(input))throw new ApiError(`${label} must be one of ${s.enum.join(', ')}.`);}
export async function executeMomence(operationId:string,params:Record<string,string>,body:unknown,confirmed:boolean,actor:{id?:number;name:string}){const op=catalogue.find(o=>o.id===operationId);if(!op)throw new ApiError('Unknown documented operation');if(op.method!=='GET'&&!confirmed)throw new ApiError('Confirm the live external change first.');if(!await momenceConfigured())throw new ApiError('Demo records are read-only. Connect Momence to perform this action.',409);let path=op.path;for(const p of op.parameters){if(p.in==='path'){const v=params[p.name];if(!v||!/^\d+$/.test(v))throw new ApiError(`${p.name} must be a numeric Momence ID.`);path=path.replace(`{${p.name}}`,v);}}const qs=new URLSearchParams();for(const p of op.parameters.filter(p=>p.in==='query')){let v=params[p.name];if(!v&&p.name==='page')v='0';if(!v&&p.name==='pageSize')v='50';if(p.required&&!v)throw new ApiError(`${p.name} is required`);if(v!==undefined&&v!=='')qs.set(p.name,v);}if(op.body)validateBody(op.body,body);const result=await momenceRequest(path+(qs.size?'?'+qs:''),op.method,op.body?body:undefined);await audit(actor,'momence.'+op.method,op.id,{params});return result;}
export function populateMember(detail:Awaited<ReturnType<typeof detailMomence>>){const m=detail.item.raw;const pack=detail.related.memberships?.[0];return{memberName:detail.item.name,memberEmail:String(m.email||''),memberPhone:String(m.phoneNumber||''),momenceMemberId:detail.item.id,membership:pack?value(pack.name||obj(pack.membership).name):undefined,momenceContext:{member:detail.item, memberships:detail.related.memberships,bookings:detail.related.bookings,source:detail.source},memberLookupDone:true};}
export function populateSession(detail:Awaited<ReturnType<typeof detailMomence>>){const s=detail.item.raw;return{classFormat:detail.item.name,trainer:value(s.teacher),studio:value(s.inPersonLocation),incidentAt:String(s.startsAt||''),momenceSessionId:detail.item.id,sessionLookupDone:true,sessionContext:{...s,bookings:detail.related.bookings,source:detail.source}};}
