import {and,desc,eq,or,sql,ne,inArray} from 'drizzle-orm';
import {randomUUID} from 'crypto';
import {db} from '@/db';
import {tickets,staff,departments,ticketActivities,ticketComments,ticketLinks,ticketResolutions,deliveryLogs} from '@/db/schema';
import {ticketInputSchema,type TicketInput,type AdvancedDraft} from './ticket-contract';
import {getConfig} from './config';
import {ApiError,currentUser} from './auth';
import {inferPriority,inferSeverity,studioIdsFor} from './routing';
import {buildTemplate} from './templates';
import {ticketNumberFor,slugify} from './utils';
import {scoreAssessment} from './guided-templates';
import {configuredTemplates} from './template-store';

export async function makeDraft(raw:unknown):Promise<AdvancedDraft>{const input=ticketInputSchema.parse(raw);const cfg=await getConfig();if(!cfg.taxonomy[input.category]?.includes(input.subcategory))throw new ApiError('Choose a subcategory belonging to the selected category.');
const template=input.templateId?(await configuredTemplates()).find(t=>t.id===input.templateId):undefined;
if(template)for(const field of template.fields.filter(f=>f.required)){const val=input.customFields[field.id];if(val===undefined||val===null||val==='')throw new ApiError(`${field.label} is required.`);if(field.type==='rating'&&(!Number.isFinite(Number(val))||Number(val)<0||Number(val)>5))throw new ApiError(`${field.label} must be scored from 0 to 5.`);}
const calculatedScore=template?scoreAssessment(template.fields,input.customFields):null;if(calculatedScore!==null)input.customFields.evaluationScore=calculatedScore;
const praise=input.kind==='compliment'||input.kind==='feedback'&&input.sentiment==='positive';const noSla=input.kind==='assessment'||praise&&cfg.positiveNoSla;
// The intake answers ride in customFields — they are not columns on the schema — so
// they have to be read back out here or the reporter's own urgency signal never
// reaches the priority rules.
const priority=noSla?'low':input.category==='Safety and Security'?'critical':input.priority||inferPriority({category:input.category,subcategory:input.subcategory,isClassImpacted:String(input.customFields.isClassImpacted||''),isImmediateDanger:String(input.customFields.isImmediateDanger||''),impact:input.impact});
const departmentId=cfg.categoryDepartments[input.category]||'operations';const[dept]=await db.select().from(departments).where(eq(departments.id,departmentId));if(!dept?.active)throw new ApiError('The routing department is inactive. Ask an administrator to update the routing rule.');
const people=await db.select().from(staff).where(and(eq(staff.isActive,true),eq(staff.department,dept.name)));
const ids=studioIdsFor(input.studio);const override=cfg.routingOwners[input.category+'::'+input.studio]||cfg.routingOwners[input.category];
const owner=cfg.autoAssign?(people.find(p=>p.id===override)||people.sort((a,b)=>{const score=(p:typeof a)=>(p.categories.includes(input.category)?10:0)+(p.studioId&&ids.includes(p.studioId)?8:0)+(/Head|Coordinator|Ops Manager|Chief/.test(p.role)?3:0);return score(b)-score(a);})[0]):{id:null,name:'Unassigned',email:'',role:'Department queue'};if(!owner)throw new ApiError('No active owner is available in the routing department.');
const title=input.title?.trim()||`${praise?'Member appreciation':input.subcategory} · ${input.studio.split(',')[0]}`;
const summary=input.summary?.trim()||input.description.replace(/\s+/g,' ').slice(0,350);
const slaHours=noSla?0:cfg.responseHours[priority];const base=buildTemplate(input.category,input.subcategory);
const opsChecklist=noSla?['Record the feedback accurately','Share recognition with the relevant team']:base.opsChecklist;
const tags=cfg.autoTag?[...new Set([slugify(input.category),slugify(input.subcategory),slugify(input.studio.split(',')[0]),input.kind,noSla?'no-sla':priority,...(input.momenceMemberId?['momence-linked']:[]),...(input.kind==='assessment'?['trainer-evaluation']:[])])]:[];
const memberFacingUpdate=praise?`Thank you${input.memberName?' , '+input.memberName.split(' ')[0]:''} for sharing this. Your feedback will be recorded for our ${dept.name} team.`:`Hi ${input.memberName.split(' ')[0]}, thank you for sharing your experience. ${owner.name} from ${dept.name} will review your request. The internal follow-up target is ${slaHours} hours; a resolution time has not yet been confirmed.`;
return{...input,title,summary,priority,severity:inferSeverity(priority),assignedStaffId:owner.id,assignedStaffName:owner.name,assignedStaffEmail:owner.email,assignedStaffRole:owner.role,departmentId,departmentName:dept.name,slaHours,slaLabel:noSla?'No SLA required':slaHours+' hours',resolutionRequired:!noSla,tags,opsChecklist,memberFacingUpdate,internalBrief:input.description,routingReason:!cfg.autoAssign?'Automatic assignment disabled · department queue':override?'Administrator-defined routing rule':`${input.category} → ${dept.name}; active studio / regional specialist`};}

export async function createTicketFromDraft(draft:AdvancedDraft,source=draft.source,channel='workspace',external?:{sourceRef?:string;createdAt?:Date;status?:string}){const cfg=await getConfig();const submissionKey=draft.submissionKey||randomUUID();return db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${submissionKey}))`);const[existing]=await tx.select().from(tickets).where(external?.sourceRef?or(eq(tickets.submissionKey,submissionKey),eq(tickets.sourceRef,external.sourceRef)):eq(tickets.submissionKey,submissionKey));if(existing)return existing;
const now=external?.createdAt||new Date();const status=external?.status||(draft.resolutionRequired?'assigned':'recorded');
const[row]=await tx.insert(tickets).values({ticketNumber:'P57-'+randomUUID(),title:draft.title,summary:draft.summary,description:draft.description,category:draft.category,subcategory:draft.subcategory,status,priority:draft.priority,severity:draft.severity,sentiment:draft.sentiment,kind:draft.kind,resolutionRequired:draft.resolutionRequired,impact:draft.impact,studio:draft.studio,classFormat:draft.classFormat,trainer:draft.trainer,membership:draft.membership,incidentAt:draft.incidentAt,memberName:draft.memberName,memberEmail:draft.memberEmail,memberPhone:draft.memberPhone,momenceMemberId:draft.momenceMemberId,momenceSessionId:draft.momenceSessionId,preferredContact:draft.preferredContact,requestedResolution:draft.requestedResolution,assignedStaffId:draft.assignedStaffId,assignedStaffName:draft.assignedStaffName,assignedStaffEmail:draft.assignedStaffEmail,departmentId:draft.departmentId,departmentName:draft.departmentName,slaHours:draft.slaHours,slaDueAt:draft.slaHours?new Date(now.getTime()+draft.slaHours*3600000):null,source,channel,tags:draft.tags,templateId:draft.templateId,customFields:{...draft.customFields,_brief:{opsChecklist:draft.opsChecklist,memberFacingUpdate:draft.memberFacingUpdate,routingReason:draft.routingReason}},momenceContext:draft.momenceContext||null,submissionKey,sourceRef:external?.sourceRef,createdAt:now,updatedAt:now,...(['resolved','closed'].includes(status)?{resolvedAt:now}:{})}).returning();const number=ticketNumberFor(row.id);await tx.update(tickets).set({ticketNumber:number}).where(eq(tickets.id,row.id));await tx.insert(ticketActivities).values({ticketId:row.id,actorName:source==='history'?'History import':'IRIS',action:'created',detail:`${draft.assignedStaffName} · ${draft.departmentName} · ${draft.slaLabel}`,createdAt:now});
if(source!=='history'&&cfg.webhookOnCreate)await tx.insert(deliveryLogs).values({integrationId:'n8n',action:'webhook',payload:{event:'ticket.created',ticket:{id:row.id,ticketNumber:number,title:draft.title,priority:draft.priority,department:draft.departmentName,assignedTo:draft.assignedStaffName}}});
if(source!=='history'&&cfg.assignmentEmail&&draft.assignedStaffEmail)await tx.insert(deliveryLogs).values({integrationId:'mailtrap',action:'send',payload:{to:[{email:draft.assignedStaffEmail}],subject:`Assigned: ${number}`,text:`${draft.title}\n\nA ticket has been assigned to you in IRIS. Please sign in to review it.`}});
return{...row,ticketNumber:number};});}
/** List views never read `customFields` or the long-form text, which are ~85% of the
 *  table's bytes. Selecting only the rendered columns keeps this response small. */
const LIST_COLUMNS={id:tickets.id,ticketNumber:tickets.ticketNumber,title:tickets.title,status:tickets.status,priority:tickets.priority,category:tickets.category,subcategory:tickets.subcategory,studio:tickets.studio,memberName:tickets.memberName,assignedStaffId:tickets.assignedStaffId,assignedStaffName:tickets.assignedStaffName,departmentName:tickets.departmentName,kind:tickets.kind,source:tickets.source,resolutionRequired:tickets.resolutionRequired,slaDueAt:tickets.slaDueAt,resolvedAt:tickets.resolvedAt,createdAt:tickets.createdAt,version:tickets.version};
export async function listTickets(){return db.select(LIST_COLUMNS).from(tickets).orderBy(desc(tickets.createdAt)).limit(2000);}
/** Resolution is private to the assigned owner or that owner's direct reporting manager. */
export async function canResolveTicket(user:{staffId:number|null;role:string}|null,assignedStaffId:number|null,resolutionRequired:boolean):Promise<boolean>{if(!user||!resolutionRequired||user.staffId===null||assignedStaffId===null)return false;if(!['admin','agent'].includes(user.role))return false;if(user.staffId===assignedStaffId)return true;const[assignee]=await db.select({manager:staff.manager}).from(staff).where(eq(staff.id,assignedStaffId));if(!assignee?.manager)return false;const[managerRow]=await db.select({id:staff.id}).from(staff).where(eq(staff.name,assignee.manager));return managerRow?.id===user.staffId;}
export async function getTicketBundle(id:number){const[[ticket],user]=await Promise.all([db.select().from(tickets).where(eq(tickets.id,id)),currentUser()]);if(!ticket)return null;
// These six reads are independent of each other. Issued sequentially they cost six database
// round-trips before anything renders; in parallel they cost one.
const[canResolve,comments,activities,similar,links]=await Promise.all([
  canResolveTicket(user,ticket.assignedStaffId,ticket.resolutionRequired),
  db.select().from(ticketComments).where(eq(ticketComments.ticketId,id)).orderBy(ticketComments.createdAt),
  db.select().from(ticketActivities).where(eq(ticketActivities.ticketId,id)).orderBy(ticketActivities.createdAt),
  db.select({id:tickets.id,ticketNumber:tickets.ticketNumber,title:tickets.title,status:tickets.status,priority:tickets.priority}).from(tickets).where(and(eq(tickets.category,ticket.category),eq(tickets.subcategory,ticket.subcategory),ne(tickets.id,id))).orderBy(desc(tickets.createdAt)).limit(8),
  db.select().from(ticketLinks).where(or(eq(ticketLinks.ticketId,id),eq(ticketLinks.relatedId,id))),
]);
const linkedIds=links.map(l=>l.ticketId===id?l.relatedId:l.ticketId);
const[linked,[resolution]]=await Promise.all([
  linkedIds.length?db.select({id:tickets.id,ticketNumber:tickets.ticketNumber,title:tickets.title,status:tickets.status}).from(tickets).where(inArray(tickets.id,linkedIds)):Promise.resolve([]),
  canResolve?db.select().from(ticketResolutions).where(eq(ticketResolutions.ticketId,id)):Promise.resolve([]),
]);
return{ticket,comments,activities,similar,linked,canResolve,resolution:resolution||null};}
const BIKE_PATTERN=/\b(bike|bikes|cycle|cycling|powercycle|power cycle|spin bike|pedal|flywheel|resistance knob)\b/i;
export function isPowerCycleBikeTicket(t:{title:string;description:string;subcategory:string;classFormat:string|null;category:string}):boolean{const haystack=`${t.title} ${t.description} ${t.subcategory} ${t.classFormat||''}`;if(!BIKE_PATTERN.test(haystack))return false;return['Repair and Maintenance','Tech Issues','Studio Amenities and Facilities'].includes(t.category)||/powercycle/i.test(t.classFormat||'');}
/** When a PowerCycle bike malfunction ticket is resolved, auto-raise a 48h relapse-check follow-up for the same owner. */
export async function maybeCreateBikeFollowUp(resolved:{id:number;ticketNumber:string;title:string;description:string;subcategory:string;category:string;classFormat:string|null;studio:string|null;assignedStaffId:number|null;assignedStaffName:string|null;assignedStaffEmail:string|null;departmentId:string|null;departmentName:string|null;memberName:string;trainer:string|null}){
  if(!isPowerCycleBikeTicket(resolved))return null;
  const[existing]=await db.select({id:tickets.id}).from(tickets).where(eq(tickets.submissionKey,'bike-followup:'+resolved.id));
  if(existing)return null;
  const slaHours=48;const now=new Date();
  const draft:AdvancedDraft={source:'system',title:`Bike relapse check — ${(resolved.studio||'Studio').split(',')[0]} (48h follow-up)`,summary:`Automatic 48-hour relapse check following resolution of ${resolved.ticketNumber} (${resolved.subcategory}). Confirm the bike/equipment has not faulted again.`,description:`This is an automatically generated 48-hour relapse-check ticket linked to ${resolved.ticketNumber} — "${resolved.title}".\n\nOriginal issue: ${resolved.description}\n\nAction required: Physically inspect the PowerCycle bike / equipment involved and confirm the original fault has not recurred. Mark this ticket resolved only after the equipment has been checked and is confirmed fully functional.`,category:resolved.category,subcategory:resolved.subcategory,kind:'issue',studio:resolved.studio||'Studio to confirm',classFormat:resolved.classFormat||undefined,trainer:resolved.trainer||undefined,membership:undefined,incidentAt:'Scheduled 48 hours after resolution',memberName:'Automated follow-up · Studio Ops',memberEmail:undefined,memberPhone:undefined,momenceMemberId:undefined,momenceSessionId:undefined,preferredContact:'Internal log only',requestedResolution:'Confirm no relapse of the original bike fault; mark resolved once verified.',priority:'medium',severity:inferSeverity('medium'),sentiment:'neutral',tags:['auto-follow-up','powercycle-bike-check','relapse-check'],customFields:{parentTicketId:resolved.id,parentTicketNumber:resolved.ticketNumber,autoFollowUp:true,followUpReason:'PowerCycle bike relapse check'},assignedStaffId:resolved.assignedStaffId,assignedStaffName:resolved.assignedStaffName||'Unassigned',assignedStaffEmail:resolved.assignedStaffEmail||'',assignedStaffRole:'Follow-up owner',departmentId:resolved.departmentId||'operations',departmentName:resolved.departmentName||'Operations',slaHours,slaLabel:slaHours+' hours',resolutionRequired:true,opsChecklist:['Physically inspect the bike / equipment','Confirm no repeat of the original fault','Log findings in the resolution notes','Escalate to maintenance vendor if the fault has recurred'],memberFacingUpdate:'',internalBrief:`48-hour relapse check for ${resolved.ticketNumber}.`,routingReason:'Auto-raised 48h relapse check, same owner as the original bike ticket.'};
  const child=await createTicketFromDraft(draft,'system','automation',{sourceRef:'bike-followup:'+resolved.id});
  await db.update(tickets).set({slaDueAt:new Date(now.getTime()+slaHours*3600000),submissionKey:'bike-followup:'+resolved.id}).where(eq(tickets.id,child.id));
  await db.insert(ticketLinks).values({ticketId:Math.min(resolved.id,child.id),relatedId:Math.max(resolved.id,child.id),relation:'follow-up'}).onConflictDoNothing();
  await db.insert(ticketActivities).values({ticketId:resolved.id,actorName:'IRIS Automation',action:'follow_up.created',detail:`Auto-raised ${child.ticketNumber} as a 48h bike relapse check.`});
  await db.insert(ticketActivities).values({ticketId:child.id,actorName:'IRIS Automation',action:'created',detail:`Auto-raised from ${resolved.ticketNumber} · due for a relapse check in 48 hours.`});
  return child;
}
export async function historicalExamples(category:string,subcategory:string){const rows=await db.select({title:tickets.title,description:tickets.description,category:tickets.category,subcategory:tickets.subcategory,memberName:tickets.memberName}).from(tickets).where(and(eq(tickets.source,'history'),eq(tickets.category,category),eq(tickets.subcategory,subcategory))).limit(3);return rows.map(r=>({category:r.category,subcategory:r.subcategory,summary:r.description.replaceAll(r.memberName,'[member]').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[email]').replace(/\+?\d[\d\s-]{8,}\d/g,'[phone]').slice(0,700)}));}
