import {eq,and,sql} from 'drizzle-orm';
import {z} from 'zod';
import {db} from '@/db';
import {tickets,staff,departments,ticketActivities,ticketResolutions,ticketLinks} from '@/db/schema';
import {ApiError,requireAgent,requireWorkspace,errorResponse,sameOrigin} from '@/lib/auth';
import {getTicketBundle,makeDraft,createTicketFromDraft,canResolveTicket,maybeCreateBikeFollowUp} from '@/lib/tickets';
import {getConfig} from '@/lib/config';
import {inferSeverity} from '@/lib/routing';
export const dynamic='force-dynamic';
type Ctx={params:Promise<{id:string}>};
export async function GET(_req:Request,ctx:Ctx){try{await requireWorkspace();const id=z.coerce.number().int().positive().parse((await ctx.params).id);const bundle=await getTicketBundle(id);if(!bundle)throw new ApiError('Ticket not found',404);return Response.json(bundle);}catch(e){return errorResponse(e);}}
export async function PATCH(req:Request,ctx:Ctx){try{sameOrigin(req);const actor=await requireAgent();const id=z.coerce.number().int().positive().parse((await ctx.params).id);const b=z.object({version:z.number().int(),status:z.enum(['new','triaged','assigned','in_progress','waiting_on_member','waiting_on_vendor','resolved','closed','recorded']).optional(),priority:z.enum(['critical','high','medium','low']).optional(),assignedStaffId:z.number().int().positive().optional(),isEscalated:z.boolean().optional(),title:z.string().min(3).max(240).optional(),description:z.string().min(12).max(20000).optional(),requestedResolution:z.string().max(2000).optional()}).parse(await req.json());const[current]=await db.select().from(tickets).where(eq(tickets.id,id));if(!current)throw new ApiError('Ticket not found',404);if(b.status==='recorded'&&current.resolutionRequired)throw new ApiError('Only record-only feedback can use Recorded status.');if(['resolved','closed'].includes(b.status||'')&&current.resolutionRequired){if(!(await canResolveTicket(actor,current.assignedStaffId,current.resolutionRequired)))throw new ApiError('Only the assigned owner or their reporting manager may resolve this ticket.',403);const[r]=await db.select().from(ticketResolutions).where(eq(ticketResolutions.ticketId,id));if(!r?.actionTaken.trim()||!r.memberOutcome.trim())throw new ApiError('Complete the private resolution action and outcome first.');
// `requireResolutionNotes` asks for the whole record, not just what was done and what the
// member was told: without a root cause and a preventive action the log cannot answer
// "has this happened before, and what did we change?".
const full=await getConfig();if(full.requireResolutionNotes&&(!r.rootCause.trim()||!r.preventiveAction.trim()))throw new ApiError('This workspace requires a root cause and a preventive action before a ticket can be resolved.');}
// Reopening is a policy decision: some teams want resolution to be final, with a fresh
// ticket raised instead of an old one being reopened weeks later.
if(b.status&&!['resolved','closed','recorded'].includes(b.status)&&['resolved','closed'].includes(current.status)){const reopen=await getConfig();if(!reopen.allowReopen)throw new ApiError('Reopening resolved tickets is switched off for this workspace. Log a new ticket that links to this one.',409);}
let ownerFields={};if(b.assignedStaffId){const[p]=await db.select().from(staff).where(and(eq(staff.id,b.assignedStaffId),eq(staff.isActive,true)));if(!p)throw new ApiError('Choose an active owner');const[d]=await db.select().from(departments).where(eq(departments.name,p.department));if(!d?.active)throw new ApiError('Owner department is inactive');ownerFields={assignedStaffId:p.id,assignedStaffName:p.name,assignedStaffEmail:p.email,departmentId:d.id,departmentName:d.name};}
const cfg=await getConfig();const sla=b.priority&&current.resolutionRequired?{slaHours:cfg.responseHours[b.priority],slaDueAt:new Date(current.createdAt.getTime()+cfg.responseHours[b.priority]*3600000),severity:inferSeverity(b.priority)}:{};
const result=await db.transaction(async tx=>{const[t]=await tx.update(tickets).set({...b,...ownerFields,...sla,version:sql`${tickets.version}+1`,updatedAt:new Date(),...(b.status==='resolved'?{resolvedAt:new Date()}:{}),...(b.status==='closed'?{closedAt:new Date()}:{}),...(b.status&&!['resolved','closed'].includes(b.status)?{resolvedAt:null,closedAt:null}:{})}).where(and(eq(tickets.id,id),eq(tickets.version,b.version))).returning();if(!t)throw new ApiError('This ticket changed elsewhere. Refresh before saving.',409);await tx.insert(ticketActivities).values({ticketId:id,actorName:actor.name,action:'updated',detail:Object.entries(b).filter(([k])=>k!=='version').map(([k,v])=>`${k}: ${v}`).join(' · ')});return t;});let followUp=null;if(b.status==='resolved')followUp=await maybeCreateBikeFollowUp(result);return Response.json({ticket:result,followUpTicket:followUp?{id:followUp.id,ticketNumber:followUp.ticketNumber}:null});}catch(e){return errorResponse(e);}}
export async function POST(req:Request,ctx:Ctx){try{sameOrigin(req);const actor=await requireAgent();const id=z.coerce.number().int().positive().parse((await ctx.params).id);const b=z.object({action:z.enum(['duplicate','link','unlink']),relatedId:z.number().int().positive().optional()}).parse(await req.json());const[t]=await db.select().from(tickets).where(eq(tickets.id,id));if(!t)throw new ApiError('Ticket not found',404);if(b.action==='duplicate'){const draft=await makeDraft({...t,title:'Copy · '+t.title,source:'manual',submissionKey:crypto.randomUUID(),memberEmail:t.memberEmail||'',memberPhone:t.memberPhone||undefined,incidentAt:t.incidentAt||'Not recorded',momenceMemberId:t.momenceMemberId||undefined,momenceSessionId:t.momenceSessionId||undefined,membership:t.membership||undefined,classFormat:t.classFormat||undefined,trainer:t.trainer||undefined,requestedResolution:t.requestedResolution||undefined,impact:t.impact||undefined,momenceContext:t.momenceContext||undefined,templateId:t.templateId||undefined,preferredContact:t.preferredContact||'Email',sentiment:t.sentiment||'neutral'});const copy=await createTicketFromDraft(draft);await db.insert(ticketLinks).values({ticketId:Math.min(id,copy.id),relatedId:Math.max(id,copy.id),relation:'duplicate'}).onConflictDoNothing();return Response.json({ticket:copy});}
if(!b.relatedId||b.relatedId===id)throw new ApiError('Choose a different ticket');const[related]=await db.select({id:tickets.id}).from(tickets).where(eq(tickets.id,b.relatedId));if(!related)throw new ApiError('Related ticket not found',404);const a=Math.min(id,b.relatedId),r=Math.max(id,b.relatedId);if(b.action==='link')await db.insert(ticketLinks).values({ticketId:a,relatedId:r}).onConflictDoNothing();else await db.delete(ticketLinks).where(and(eq(ticketLinks.ticketId,a),eq(ticketLinks.relatedId,r)));await db.insert(ticketActivities).values({ticketId:id,actorName:actor.name,action:b.action,detail:'Ticket '+b.relatedId});return Response.json({ok:true});}catch(e){return errorResponse(e);}}
