import 'dotenv/config';
import assert from 'node:assert/strict';
import {randomBytes,scryptSync,randomUUID} from 'node:crypto';
import {eq,inArray} from 'drizzle-orm';
import {db,pool} from '../src/db/index.ts';
import {appUsers,appSettings,tickets,chatSessions,chatMessages,auditLogs} from '../src/db/schema.ts';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
function client(){const cookies=new Map();return async(path,method='GET',body)=>{const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:[...cookies].map(([k,v])=>k+'='+v).join('; ')},body:body===undefined?undefined:JSON.stringify(body)});for(const line of res.headers.getSetCookie()){const part=line.split(';')[0],index=part.indexOf('=');cookies.set(part.slice(0,index),part.slice(index+1));}return{status:res.status,body:await res.json()};};}
const admin=client(),owner=client(),viewer=client(),anon=client();const userIds=[],createdTickets=[],chatIds=[];const originalSettings=await db.select().from(appSettings).where(eq(appSettings.key,'workspace'));
const password=randomBytes(24).toString('base64url'),salt=randomBytes(16).toString('hex'),passwordHash=salt+':'+scryptSync(password,salt,64).toString('hex');
try{
assert.equal((await anon('/api/health')).status,200);
const used=await db.select({staffId:appUsers.staffId}).from(appUsers);const staffId=[31,24,19,3,16,9].find(id=>!used.some(u=>u.staffId===id));assert.ok(staffId,'A spare staff profile is needed for isolated API tests');
const stamp=Date.now();for(const [role,staffIdValue]of [['admin',null],['agent',staffId],['viewer',null]]){const email=`iris-test-${role}-${stamp}@example.invalid`;const[u]=await db.insert(appUsers).values({name:'IRIS QA '+role,email,passwordHash,role,staffId:staffIdValue}).returning();userIds.push(u.id);const c=role==='admin'?admin:role==='agent'?owner:viewer;assert.equal((await c('/api/auth','POST',{action:'login',email,password})).status,200);}
assert.equal((await anon('/api/tickets')).status,401);
let settings=(await admin('/api/settings')).body;assert.ok(settings.config);const cfg={...settings.config,webhookOnCreate:false,assignmentEmail:false,autoAssign:true,responseHours:{...settings.config.responseHours,medium:12}};assert.equal((await admin('/api/settings','PUT',{config:cfg,version:settings.version})).status,200);assert.equal((await admin('/api/settings')).body.config.responseHours.medium,12);assert.equal((await viewer('/api/settings')).status,403);
assert.equal((await owner('/api/preferences','PATCH',{theme:'dark',view:'cards'})).status,200);let prefs=(await owner('/api/preferences')).body;assert.equal(prefs.theme,'dark');assert.equal(prefs.view,'cards');
const input={description:'Synthetic regression ticket: the class waitlist confirmation did not arrive.',category:'Scheduling',subcategory:'Waitlist Concerns',kind:'issue',studio:'Kwality House, Kemps Corner',memberName:'QA Member',memberEmail:'qa-member@example.invalid',classFormat:'Studio Barre 57',trainer:'Anisha Shah',incidentAt:'Today',source:'manual',submissionKey:randomUUID()};
let first=await admin('/api/tickets','POST',input);assert.equal(first.status,201,JSON.stringify(first.body));let t=first.body.ticket;createdTickets.push(t.id);assert.ok(t.assignedStaffId);assert.ok(t.tags.length);assert.ok(t.slaDueAt);assert.equal((await admin('/api/tickets','POST',input)).body.ticket.id,t.id,'Idempotency must return the same ticket');
let assigned=await admin('/api/tickets/'+t.id,'PATCH',{assignedStaffId:staffId,version:t.version});assert.equal(assigned.status,200,JSON.stringify(assigned.body));t=assigned.body.ticket;
const res={rootCause:'QA diagnosis',actionTaken:'QA correction completed',preventiveAction:'Regression coverage',memberOutcome:'QA outcome confirmed'};
assert.equal((await admin('/api/tickets/'+t.id+'/resolution','PUT',res)).status,403,'Admin is not an assigned-owner bypass');assert.equal((await viewer('/api/tickets/'+t.id+'/resolution','PUT',res)).status,403);assert.equal((await owner('/api/tickets/'+t.id+'/resolution','PUT',res)).status,200);assert.equal((await owner('/api/tickets/'+t.id)).body.resolution.rootCause,'QA diagnosis');assert.equal((await viewer('/api/tickets/'+t.id)).body.resolution,null);assert.equal((await admin('/api/tickets/'+t.id)).body.resolution,null);
assert.equal((await viewer('/api/tickets/'+t.id,'PATCH',{status:'resolved',version:t.version})).status,403);const done=await owner('/api/tickets/'+t.id,'PATCH',{status:'resolved',version:t.version});assert.equal(done.status,200,JSON.stringify(done.body));assert.equal((await owner('/api/tickets/'+t.id,'PATCH',{status:'in_progress',version:t.version})).status,409,'Optimistic revisions must protect concurrent edits');
const copied=await admin('/api/tickets/'+t.id,'POST',{action:'duplicate'});assert.equal(copied.status,200,JSON.stringify(copied.body));createdTickets.push(copied.body.ticket.id);assert.ok((await admin('/api/tickets/'+t.id)).body.linked.some(x=>x.id===copied.body.ticket.id));
const positive=await admin('/api/tickets','POST',{...input,submissionKey:randomUUID(),kind:'compliment',sentiment:'positive',description:'Synthetic positive feedback: a thoughtful and uplifting studio experience.'});assert.equal(positive.status,201,JSON.stringify(positive.body));createdTickets.push(positive.body.ticket.id);assert.equal(positive.body.ticket.slaDueAt,null);assert.equal(positive.body.ticket.resolutionRequired,false);assert.equal(positive.body.ticket.status,'recorded');
const templates=(await admin('/api/templates')).body.templates;assert.ok(templates.length>250);assert.ok(templates.some(t=>t.id==='hosted-class-feedback'));assert.ok(templates.some(t=>t.id==='trainer-assessment-3'));
const start=await owner('/api/iris/chat','POST',{preset:{category:'Class Experience',subcategory:'Instructor Energy and Motivation'}});assert.equal(start.status,200);let turn=start.body;chatIds.push(turn.sessionId);turn=(await owner('/api/iris/chat','POST',{sessionId:turn.sessionId,message:'The class was wonderful and uplifting. I loved every moment and want to share a compliment.'})).body;assert.equal(turn.lookup,'members');
const mode=(await owner('/api/momence?action=status')).body;
if(!mode.configured){const ms=(await owner('/api/momence?module=members')).body;assert.equal(ms.source,'demo');assert.ok(ms.items.length);turn=(await owner('/api/iris/chat','POST',{sessionId:turn.sessionId,selection:{module:'members',id:ms.items[0].id}})).body;assert.equal(turn.lookup,'sessions');const sessions=(await owner('/api/momence?module=sessions')).body;turn=(await owner('/api/iris/chat','POST',{sessionId:turn.sessionId,selection:{module:'sessions',id:sessions.items[0].id}})).body;assert.equal(turn.phase,'draft',JSON.stringify(turn));assert.ok(turn.draft.memberEmail);assert.ok(turn.draft.momenceSessionId);assert.equal(turn.draft.resolutionRequired,false);assert.equal((await viewer('/api/iris/approve','POST',{sessionId:turn.sessionId})).status,403);const approval=await owner('/api/iris/approve','POST',{sessionId:turn.sessionId});assert.equal(approval.status,200,JSON.stringify(approval.body));createdTickets.push(approval.body.ticket.id);const again=await owner('/api/iris/approve','POST',{sessionId:turn.sessionId});assert.equal(again.body.ticket.id,approval.body.ticket.id);assert.equal((await owner('/api/iris/chat?sessionId='+turn.sessionId)).body.phase,'complete');assert.equal((await admin('/api/iris/chat?sessionId='+turn.sessionId)).status,404);}
assert.equal((await viewer('/api/momence','POST',{operationId:'authenticate'})).status,403);assert.equal((await viewer('/api/integrations','POST',{id:'n8n',action:'webhook',confirmed:true})).status,403);assert.equal((await admin('/api/history','POST',{})).status,404,'Missing history must not be fabricated');
console.log('PASS: authenticated roles, private resolutions, idempotency, conflicts, duplicate linking, no-SLA compliments, template inventory, Momence auto-fill, persistent chat approval and settings.');
}finally{
if(createdTickets.length)await db.delete(tickets).where(inArray(tickets.id,createdTickets));
if(chatIds.length){await db.delete(chatMessages).where(inArray(chatMessages.sessionId,chatIds));await db.delete(chatSessions).where(inArray(chatSessions.id,chatIds));}
await db.delete(appSettings).where(eq(appSettings.key,'workspace'));for(const s of originalSettings)await db.insert(appSettings).values(s);
if(userIds.length){await db.delete(appSettings).where(inArray(appSettings.key,userIds.map(id=>'preferences:user:'+id)));await db.delete(auditLogs).where(inArray(auditLogs.actorId,userIds));await db.delete(appUsers).where(inArray(appUsers.id,userIds));}
await pool.end();
}
