import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.goto(base,{waitUntil:'networkidle'});await page.locator('.data-table tbody tr').first().waitFor();await page.screenshot({path:'/tmp/iris-overview-light.png',fullPage:true});
await page.getByRole('button',{name:'Toggle light and dark theme'}).click();await page.waitForTimeout(300);assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({path:'/tmp/iris-overview-dark.png',fullPage:true});await page.getByRole('button',{name:'Toggle light and dark theme'}).click();
await page.getByRole('button',{name:'Board view',exact:true}).click();await page.locator('.kanban').waitFor();await page.getByRole('button',{name:'Card view',exact:true}).click();await page.locator('.ticket-cards-grid').waitFor();await page.getByRole('button',{name:'List view',exact:true}).click();
await page.locator('.data-table tbody tr').first().click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Related',exact:false}).first().click();await page.getByRole('button',{name:'Link a ticket',exact:true}).click();assert.equal(await page.locator('[role="dialog"]').count(),2);await page.keyboard.press('Escape');await page.waitForTimeout(400);assert.equal(await page.getByRole('dialog').count(),0);
await page.goto(base+'/templates',{waitUntil:'networkidle'});const buttons=page.locator('.template-card');const count=await buttons.count();assert.ok(count>=5);for(let i=0;i<count;i++){await buttons.nth(i).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.waitForTimeout(160);assert.equal(await page.getByRole('dialog').count(),0);}await page.locator('.template-card').filter({hasText:'A moment worth celebrating'}).click();await page.screenshot({path:'/tmp/iris-template-modal.png',fullPage:true});await page.keyboard.press('Escape');
await page.goto(base+'/momence',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Sessions',exact:true}).click();await page.locator('.entity-card').first().waitFor();const scroll=await page.locator('.module-scroll').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight}));assert.ok(scroll.scroll>scroll.client,'Session module must overflow vertically');await page.locator('.module-scroll').evaluate(el=>el.scrollTop=500);assert.ok(await page.locator('.module-scroll').evaluate(el=>el.scrollTop)>0);await page.locator('.entity-card').first().click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Cancellations',exact:false}).click();await page.screenshot({path:'/tmp/iris-session-detail.png',fullPage:true});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Table view',exact:true}).click();await page.locator('.data-table').waitFor();await page.getByRole('button',{name:'Members',exact:true}).click();await page.locator('.entity-card').first().waitFor();await page.locator('.entity-card').first().click();await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByText('Sample note:',{exact:false}).waitFor();await page.keyboard.press('Escape');
await page.goto(base+'/analytics',{waitUntil:'networkidle'});await page.locator('.chart-svg').waitFor();await page.screenshot({path:'/tmp/iris-reports.png',fullPage:true});
await page.goto(base+'/iris',{waitUntil:'networkidle'});await page.getByRole('textbox',{name:'Message Iris'}).fill('I loved Studio Barre 57 with Anisha Shah yesterday. The class was wonderful.');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.waitForTimeout(700);await page.screenshot({path:'/tmp/iris-conversation.png',fullPage:true});assert.ok(!await page.getByText('Noted —').count());
await page.goto(base+'/settings',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:'Dark · understated luxury',exact:false}).waitFor();
await page.setViewportSize({width:390,height:844});await page.goto(base,{waitUntil:'networkidle'});await page.screenshot({path:'/tmp/iris-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile viewport must not overflow');assert.deepEqual(errors,[]);console.log('PASS: navigation, all featured templates, Escape closes nested modals, module scrolling, views, notes, themes, reports, Iris and mobile layout.');
}finally{await browser.close();}
