import 'dotenv/config';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {eq} from 'drizzle-orm';import fs from 'node:fs';
import {listMomence,detailMomence,executeMomence} from '../src/lib/momence.ts';import {db,pool} from '../src/db/index.ts';import {auditLogs} from '../src/db/schema.ts';
const catalogue=JSON.parse(fs.readFileSync('src/lib/momence-catalogue.json','utf8'));const keys=['MOMENCE_USERNAME','MOMENCE_PASSWORD','MOMENCE_CLIENT_ID','MOMENCE_CLIENT_SECRET'];const previous=Object.fromEntries(keys.map(k=>[k,process.env[k]]));for(const k of keys)process.env[k]=randomBytes(16).toString('hex');
const token=randomBytes(24).toString('hex'),originalFetch=globalThis.fetch;let tokenCalls=0;const mutations=[];
const member={id:701,firstName:'QA',lastName:'Member',email:'qa@example.invalid',phoneNumber:'+910000000000',visits:{totalVisits:42}};
const session={id:801,name:'Studio Barre 57',teacher:{id:5,firstName:'QA',lastName:'Trainer'},inPersonLocation:{id:1,name:'Kwality House, Kemps Corner'},startsAt:'2026-01-01T10:00:00Z',bookingCount:17,capacity:24,isCancelled:false};
const response=data=>Response.json(data);
globalThis.fetch=async(url,init={})=>{const u=new URL(String(url));assert.equal(u.hostname,'api.momence.com','Tests must not reach a real external account');if(u.pathname==='/api/v2/auth/token'){tokenCalls++;assert.equal(init.method,'POST');const data=new URLSearchParams(String(init.body));assert.equal(data.get('grant_type'),'password');assert.equal(data.get('username'),process.env.MOMENCE_USERNAME);assert.equal(init.headers.Authorization,'Basic '+Buffer.from(process.env.MOMENCE_CLIENT_ID+':'+process.env.MOMENCE_CLIENT_SECRET).toString('base64'));return response({accessToken:token,refreshToken:randomBytes(12).toString('hex'),accessTokenExpiresAt:new Date(Date.now()+3600000).toISOString()});}assert.equal(init.headers.Authorization,'Bearer '+token);if(init.method&&init.method!=='GET'){mutations.push({method:init.method,path:u.pathname,body:init.body?JSON.parse(init.body):null});return init.method==='DELETE'?new Response(null,{status:204}):response({id:702,ok:true});}
if(u.pathname==='/api/v2/host/members')return response({payload:[member],pagination:{totalCount:1}});if(u.pathname==='/api/v2/host/sessions')return response({payload:[session],pagination:{totalCount:1}});if(u.pathname==='/api/v2/host/members/701')return response(member);if(u.pathname.endsWith('/bought-memberships/active')){assert.equal(u.searchParams.get('includeFrozen'),'true');return response({payload:[{id:901,membership:{id:100,name:'Barre Annual Membership'},isFrozen:true,eventCreditsLeft:8}]});}if(u.pathname==='/api/v2/host/members/701/sessions'){assert.equal(u.searchParams.get('includeCancelled'),'true');return response({payload:[{id:111,session,cancelledAt:null,checkedIn:true}]});}if(u.pathname.endsWith('/notes'))return response({payload:[{id:333,note:'QA note',type:'regular'}]});throw new Error('Unexpected mocked path: '+u.pathname);};
try{const members=await listMomence('members');assert.equal(members.source,'live');assert.equal(members.items[0].name,'QA Member');assert.equal(members.items[0].raw.visits.totalVisits,42);const sessions=await listMomence('sessions');assert.equal(sessions.items[0].subtitle,'QA Trainer · Kwality House, Kemps Corner');assert.equal(sessions.items[0].raw.bookingCount,17);const ctx=await detailMomence('members','701');assert.equal(ctx.related.notes[0].note,'QA note');assert.equal(ctx.related.memberships[0].membership.name,'Barre Annual Membership');assert.equal(ctx.related.bookings[0].session.id,801);
const edit=catalogue.find(o=>o.method==='PUT'&&o.path.endsWith('/members/{memberId}/name'));await assert.rejects(()=>executeMomence(edit.id,{memberId:'701'},{firstName:'QA',lastName:'Update'},false,{name:'Mock verification'}),/Confirm/);await executeMomence(edit.id,{memberId:'701'},{firstName:'QA',lastName:'Update'},true,{name:'Mock verification'});
const create=catalogue.find(o=>o.method==='POST'&&o.path==='/api/v2/host/members');await executeMomence(create.id,{}, {firstName:'QA',lastName:'Created',email:'qa-created@example.invalid'},true,{name:'Mock verification'});
const unfreeze=catalogue.find(o=>o.method==='DELETE'&&o.path.endsWith('/membership-schedule-freeze'));await executeMomence(unfreeze.id,{memberId:'701',boughtMembershipId:'901'},undefined,true,{name:'Mock verification'});assert.deepEqual(mutations.map(m=>m.method),['PUT','POST','DELETE']);assert.equal(tokenCalls,1,'Access token should be cached until expiry');console.log('PASS: username/password token exchange, Basic client authentication, Bearer reuse, nested member/session data, notes/bookings endpoints and confirmed PUT/POST/DELETE payloads.');
}finally{globalThis.fetch=originalFetch;for(const k of keys){if(previous[k]===undefined)delete process.env[k];else process.env[k]=previous[k];}await db.delete(auditLogs).where(eq(auditLogs.actorName,'Mock verification'));await pool.end();}
