import {NextRequest} from 'next/server';import {z} from 'zod';import {eq,desc,sql} from 'drizzle-orm';
import {db} from '@/db';import {appSettings,appUsers,staff,departments,auditLogs,deliveryLogs,importRuns,tickets} from '@/db/schema';
import {requireAdmin,errorResponse,ApiError,sameOrigin} from '@/lib/auth';import {getConfig,configSchema,audit} from '@/lib/config';
import {configuredTemplates,guidedTemplateSchema} from '@/lib/template-store';
import {relabelTickets} from '@/lib/relabel';
export const dynamic='force-dynamic';
export async function GET(req:NextRequest){try{const cfg=await getConfig();if(req.nextUrl.searchParams.get('scope')==='public')return Response.json({workspaceName:cfg.workspaceName,taxonomy:cfg.taxonomy,studios:cfg.studios,trainers:cfg.trainers,formats:cfg.formats,memberships:cfg.memberships,defaultTheme:cfg.defaultTheme,pollSeconds:cfg.pollSeconds,timezone:cfg.timezone,staleTicketDays:cfg.staleTicketDays,dateFormat:cfg.dateFormat,weekStartsOn:cfg.weekStartsOn,currency:cfg.currency,appearancePreset:cfg.appearancePreset,appearanceScale:cfg.appearanceScale,appearanceSpacing:cfg.appearanceSpacing,appearanceRadius:cfg.appearanceRadius,appearanceShadow:cfg.appearanceShadow,appearanceDensity:cfg.appearanceDensity,appearanceCardStyle:cfg.appearanceCardStyle});await requireAdmin();const[setting]=await db.select().from(appSettings).where(eq(appSettings.key,'workspace'));const table=req.nextUrl.searchParams.get('table');if(table){let rows:unknown[]=[];if(table==='staff')rows=await db.select().from(staff);else if(table==='departments')rows=await db.select().from(departments);else if(table==='templates')rows=await configuredTemplates();else if(table==='tickets')rows=await db.select().from(tickets).orderBy(desc(tickets.createdAt)).limit(250);else if(table==='audit')rows=await db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(100);else if(table==='deliveries')rows=await db.select().from(deliveryLogs).orderBy(desc(deliveryLogs.createdAt)).limit(100);else if(table==='imports')rows=await db.select().from(importRuns).orderBy(desc(importRuns.createdAt)).limit(50);else throw new ApiError('Unknown table');return Response.json({rows,editable:['staff','departments','templates'].includes(table)});}return Response.json({config:cfg,version:setting?.version||0,users:await db.select({id:appUsers.id,email:appUsers.email,name:appUsers.name,role:appUsers.role,staffId:appUsers.staffId,active:appUsers.active}).from(appUsers)});}catch(e){return errorResponse(e);}}
export async function PUT(req:Request){try{sameOrigin(req);const user=await requireAdmin();const b=z.object({config:configSchema,version:z.number().int()}).parse(await req.json());const version=await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(578102)`);const[prev]=await tx.select().from(appSettings).where(eq(appSettings.key,'workspace'));if((prev?.version||0)!==b.version)throw new ApiError('Settings changed in another session. Refresh before saving.',409);const deps=await tx.select().from(departments);for(const id of Object.values(b.config.categoryDepartments))if(!deps.some(d=>d.id===id&&d.active))throw new ApiError('A routing rule refers to an inactive or missing department: '+id);for(const c of Object.keys(b.config.taxonomy))if(!b.config.categoryDepartments[c])throw new ApiError('Add a department route for '+c);const activeStaff=await tx.select().from(staff);for(const[rule,id]of Object.entries(b.config.routingOwners)){const category=rule.split('::')[0],department=deps.find(d=>d.id===b.config.categoryDepartments[category]);if(!activeStaff.some(p=>p.id===id&&p.isActive&&p.department===department?.name))throw new ApiError('Routing owner must be active and in the selected department: '+rule);}const updated=b.version+1;await tx.insert(appSettings).values({key:'workspace',value:b.config,version:updated,updatedBy:user.id}).onConflictDoUpdate({target:appSettings.key,set:{value:b.config,version:updated,updatedBy:user.id,updatedAt:new Date()}});return updated;});await audit(user,'settings.updated','workspace',{version});return Response.json({ok:true,version});}catch(e){return errorResponse(e);}}
export async function PATCH(req:Request){try{sameOrigin(req);const user=await requireAdmin();const b=z.object({table:z.enum(['staff','departments','templates']),record:z.record(z.string(),z.unknown())}).parse(await req.json());if(b.table==='templates'){const template=guidedTemplateSchema.parse(b.record);const cfg=await getConfig();if(!cfg.taxonomy[template.category]?.includes(template.subcategory))throw new ApiError('Template category and subcategory must match the workspace taxonomy.');await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(578103)`);const[old]=await tx.select().from(appSettings).where(eq(appSettings.key,'template-overrides'));const value={...old?.value,[template.id]:template};await tx.insert(appSettings).values({key:'template-overrides',value,updatedBy:user.id}).onConflictDoUpdate({target:appSettings.key,set:{value,updatedBy:user.id,updatedAt:new Date()}});});}else if(b.table==='staff'){const r=z.object({id:z.number().int().positive(),externalId:z.string().min(1),name:z.string().min(2).max(120),email:z.string().email(),role:z.string().min(1),department:z.string().min(1),location:z.string().min(1),manager:z.string().nullable(),studioId:z.number().int().nullable(),categories:z.array(z.string()).min(1),avatarColor:z.string().regex(/^#[a-fA-F0-9]{6}$/),isActive:z.boolean()}).parse(b.record);const[d]=await db.select().from(departments).where(eq(departments.name,r.department));if(!d)throw new ApiError('Choose an existing department name.');await db.insert(staff).values(r).onConflictDoUpdate({target:staff.id,set:r});await db.update(tickets).set({assignedStaffName:r.name,assignedStaffEmail:r.email,updatedAt:new Date()}).where(eq(tickets.assignedStaffId,r.id));}else{const r=z.object({id:z.string().regex(/^[a-z0-9-]+$/),name:z.string().min(2),description:z.string(),active:z.boolean()}).parse(b.record);await db.transaction(async tx=>{const[prev]=await tx.select().from(departments).where(eq(departments.id,r.id));await tx.insert(departments).values(r).onConflictDoUpdate({target:departments.id,set:r});if(prev&&prev.name!==r.name){await tx.update(staff).set({department:r.name}).where(eq(staff.department,prev.name));await tx.update(tickets).set({departmentName:r.name}).where(eq(tickets.departmentId,r.id));}});}await audit(user,'table.record_saved',b.table,{id:b.record.id});return Response.json({ok:true});}catch(e){return errorResponse(e);}}

/**
 * Maintenance actions an administrator can run from the settings screen.
 *
 * `relabel` rewrites historical ticket titles so they describe the issue rather than
 * repeating the taxonomy. It defaults to a dry run: the response shows exactly what would
 * change, and nothing is written until `apply` is set.
 */
export async function POST(req:NextRequest){try{
  sameOrigin(req);
  const user=await requireAdmin();
  const b=z.object({
    action:z.literal('relabel'),
    apply:z.boolean().default(false),
    /** Also rewrite titles somebody typed by hand. Off by default. */
    force:z.boolean().default(false),
  }).parse(await req.json());

  const outcome=await relabelTickets({dryRun:!b.apply,force:b.force});
  if(b.apply)await audit(user,'tickets.relabelled','tickets',{changed:outcome.changed,scanned:outcome.scanned,force:b.force});
  return Response.json({...outcome,applied:b.apply});
}catch(e){return errorResponse(e);}}
